### ISSUE TITLE
Cadastro Evento

### ISSUE THREAD

**Issue by fabiosampaio12** [SERMIL/portal#107]
O usuário do sistema ao tentar cadastrar o evento Excesso de Contingente OM, referente ao GPT "B" o sistema está apresentando a mensagem de erro anexa. 
RA 070123030952 - (RA testado)
![evento excesso](https://cloud.githubusercontent.com/assets/12251958/8905846/11813870-3440-11e5-83d6-f8228d21ceb4.JPG)
![evento excesso1](https://cloud.githubusercontent.com/assets/12251958/8905847/1181ac10-3440-11e5-8450-2c28aa2bcf0c.JPG)

**Comment by 6975usa** [comment]
Distribui para o Sgt Borges pois vamos resolver esse bug juntos, a quatro maos, para o Borges comecar a se familiarizar com o sistema, e pra ele pegar experiencia.

**Comment by andremb2211** [comment]
O erro foi corrigido  e foi criado arquivo XML (CidadaoEventoAction-validation) para validar o formulário.

**Comment by 6975usa** [comment]
Corrigido pelo Sgt Borges

**Comment by obandrade** [comment]
Amigos desenvolvedores do SERMIL, boa tarde!
Existe alguma relação descritiva para o significado de cada nº de Evento apresentado numa consulta à seção Auditoria, no SERMIL?
Por exemplo: EVENTO: 3, Evento:22... etc...
Agradeço se a resposta puder ser encaminhada para "obandrade@hotmail.com".

**Comment by wagnerlopes** [comment]
Os eventos seguem esta numeracao:

    1 = Alistamento
    2 = Adiamento de Incorporação
    3 = Dispensa de Seleção
    4 = Seleção
    5 = Grau de Recurso na Seleção
    6 = Excesso de Contingente
    7 = Distribuição
    8 = Insubmissão
    9 = Incorporação
   10 = Qualificação
   11 = Engajamento
   12 = Licenciamento
   13 = Anulação de Incorporação
   14 = Desincorporação
   15 = Exclusão a bem da Disciplina
   16 = Deserção
   17 = Interrupção de Curso
   18 = Reforma
   19 = Desaparecimento
   20 = Extravio
   21 = Reinclusão
   22 = Transferência
   23 = Refratário LSM
   24 = Reabilitação
   25 = Falecimento


Att,

Cel Abreu Lopes

Em 29 de agosto de 2016 17:07, obandrade <notifications@github.com>
escreveu:

**Comment by obandrade** [comment]
Prezado Coronel, satisfeito, agradeço imensamente pela gentileza da resposta solicitada no GitHub, neste endereço.

Sei de vossa elevada ocupação, mas na medida do possível, prezado Coronel, solicito ainda que seja verificada a possibilidade de considerar nossas sugestões remetidas a esse desenvolvedor, respeitadas é claro, as viabilidades.

Um forte abraço a toda a equipe de desenvolvedores e parabéns pela busca incansável da máxima funcionalidade de nosso querido SERMIL! 

1º Ten QAO Topo Oséas Bezerra de Andrade
Delegado da 18ª Del SM - Vitória/ES
(27) 3132-7051 e (27) 3132-7051
(27) 9 9823-5102


Date: Wed, 31 Aug 2016 08:38:41 -0700
