### ISSUE TITLE
Impressao de CDI quando PDF aberto no browser falha

### ISSUE THREAD

**Issue by 6975usa** [SERMIL/portal#108]
Impressão de CDI funciona apenas quando o CDI gerado no Sermil é aberto no Adobe Reader.
No entanto se o CDI é aberto no visualizador de PDF do próprio browser, a impressão das informações no CDI fica deslocada para cima.

**Comment by wagnerlopes** [comment]
@6975usa 
Impressão de formulário pré-impresso é sempre um problema, acho que a solução é fazer um help informando os usuários do procedimento correto para imprimir.
