### ISSUE TITLE
Sessoes de usuarios duplicadas

### ISSUE THREAD

**Issue by fabiosampaio12** [SERMIL/portal#109]
![capturar](https://cloud.githubusercontent.com/assets/12251958/8960306/aebd5a5a-35e5-11e5-8613-a3c9c9b84e95.JPG)

**Comment by 6975usa** [comment]
![untitled](https://cloud.githubusercontent.com/assets/6667748/9011743/a371af06-3785-11e5-9f25-4a6a34075615.png)

Ser'a que o Sampaio tem homonimo de nome e posto em outro quartel?

**Comment by wagnerlopes** [comment]
@6975usa @fabiosampaio12 
Estranho isso ter começado agora. 
Precisamos analisar.

**Comment by wagnerlopes** [comment]
Será corrigido quando o Spring Security for atualizado para a versão 4.0, mas como requer muita alteração no aplicativo Portal, ficará para uma fase mais tranquila do ano.
