### ISSUE TITLE
Carregamento arquivo CTA erro

### ISSUE THREAD

**Issue by aryene** [SERMIL/portal#110]
Secretário da JSM 107 de Jacuí-MG, José Maurício Pereirae está
tendo problemas com carregamento de arquivos CTA no SERMIL

![imagem sermil](https://cloud.githubusercontent.com/assets/3015989/8984030/3e9abb8a-36a5-11e5-8bfd-f4c31b6f1f54.png)

**Comment by wagnerlopes** [comment]
Aryenne,
Quando informarem erros assim, peça que enviem o arquivo para que possamos testar.
Tente sempre coletar o máximo de informações para podermos repetir o erro no nosso ambiente de teste.
Ficamos com poucos dados para encontrar o bug no sistema.

**Comment by wagnerlopes** [comment]
@aryene veja a mensagem acima.

**Comment by aryene** [comment]
Conforme.
