### ISSUE TITLE
Problema no sistema

### ISSUE THREAD

**Issue by aryene** [SERMIL/portal#111]
SO Mangia, informou esse problema.
![sermil](https://cloud.githubusercontent.com/assets/3015989/8984149/218ce80a-36a6-11e5-8db0-1f8e10878359.png)

**Comment by 6975usa** [comment]
Testei esse erro e ele refere-se ao seguinte:

Essa falha ocorre toda vez que alguém tenta salvar um evento para cidadão com data superior a hoje.
O sistema só está permitindo que a data do evento seja igual ou menor que a data da inclusão do evento (hoje).

Pergunto ao Cel Abreu se:
1) Muda a regra de negocio para permitir qualquer data: ou
2) Cria validação para impedir datas maiores que hoje.

**Comment by wagnerlopes** [comment]
Melhor criar validação.
Eu já sei o que é, tem uma regra na classe CidEvento no método set da data que causa esse erro.
Vamos criar a validação no formulário.
Datas entre 01/01/1950 e data atual.

**Comment by 6975usa** [comment]
Esse issue ta repetido e ja foi resolvido pelo Sgt Borges.
ver:  Cadastro Evento #107 

Bom trabalho Borges. Primeiro bug resolvido. Parabens.

Foi criada uma validacao para impedir datas diferentes das permitidas no metodo setData do CidEvento.
