### ISSUE TITLE
CAM - impressao - alteracao de regra de negocio 

### ISSUE THREAD

**Issue by 6975usa** [SERMIL/portal#112]
Mudar regra de negocio para que cidadaos depois da fase de alistado tambem possam imprimir.

**Comment by wagnerlopes** [comment]
Condição de impressão, não permitir para situação militar:

* Incorporados (12);
* Licenciados (15);
* Excluídos (0);

Demais ok.

**Comment by 6975usa** [comment]
OK 
vou providenciar

**Comment by wagnerlopes** [comment]
Já fiz alteração no código.
