### ISSUE TITLE
Alteração de Tributação 

### ISSUE THREAD

**Issue by fabiosampaio12** [SERMIL/portal#121]
Para evitar problemas na Seleção Geral, quando há alteração de tributação de JSM não tributária para JSM Tributária, as RM estão esquecendo de lançar número de CS e consequentemente não está sendo enviado cidadão para CS, devido ao não cadastramento da mesma, portanto, tornar o ítem número de CS obrigatório, para as seguintes tributações é primordial para o bom andamento dos trabalhos.
- OM ativa/ OFOR
- OM ativa/ TG
- Tiro de Guerra
- OM ativa

**Comment by 6975usa** [comment]
Foi criado um metodo em JsmServico para verificar se a atribuicao de CS está correta e de acordo com as regras de negocio.
