### ISSUE TITLE
Classes anteriores conseguem se alistar online

### ISSUE THREAD

**Issue by 6975usa** [SERMIL/portal#128]
a 19 CSM informa que cidadaos de classes anteriores conseguem se alistar online.

**Comment by 6975usa** [comment]
@fabiosampaio12 Me parece que esta rotina está correta. 
Favor ver issue #97
Se não me engano, Cel @wagnerlopes  implementou que quando cidadao fora do prazo se alista, ele recebe um boleto tambem para imprimir e pagar.

**Comment by wagnerlopes** [comment]
Sim, o cidadão fora do prazo alista **ONLINE normalmente**, e recebe um link para gerar a GRU e pagar a multa antes de comparecer na JSM.
No Protocolo de alistamento vai escrito **FORA DO PRAZO**. Caso ele não pague a GRU é responsabilidade da JSM solicitar o comprovante de pagamento, e caso não possua, fazer um boleto e mandar o cidadão pagar a multa. Bem simples, qualquer pessoa com um conhecimento mediano consegue fazer isso. Ok?

**Comment by wagnerlopes** [comment]
Sim, o cidadão fora do prazo alista **ONLINE normalmente**, e recebe um link para gerar a GRU e pagar a multa antes de comparecer na JSM.
No Protocolo de alistamento vai escrito **FORA DO PRAZO**. Caso ele não pague a GRU é responsabilidade da JSM solicitar o comprovante de pagamento, e caso não possua, fazer um boleto e mandar o cidadão pagar a multa. Bem simples, qualquer pessoa com um conhecimento mediano consegue fazer isso. Ok?
