### ISSUE TITLE
Exclusao de arquivo de RA

### ISSUE THREAD

**Issue by 6975usa** [SERMIL/portal#129]
O Ten Sampaio solicita que seja criada uma rotina para exclusao de arquivo de RA.
Tal solicatacao  se deve ao fato de que ha varias solicitacoes de usuarios nesse sentido. Isso demanda muito tempo de administracao e tambem do pessoal de desenvolvimento e banco de dados.

**Comment by wagnerlopes** [comment]
Acho que não é o caso, mas precisa analisar com cuidado essas solicitações de exclusão. Pode gerar problema se não for feita com cuidado.
