### ISSUE TITLE
Padrões Funcionais 

### ISSUE THREAD

**Issue by fabiosampaio12** [SERMIL/portal#13]
O documento PDF que contém os padrões funcionais, no menu OM/Boletim de Necessidade (padrões funcionais), está quebrado. Peço a gentileza de verificar e se possível, disponibilizar para que as OM's possan lançar o Boletim de Necessidade.

**Comment by wagnerlopes** [comment]
O arquivo PDF que o link chama está faltando no sistema. Ele se encontrava na pasta docs da aplicação ROOT do Tomcat que não foi migrada para a instalação do CITEx.
Na pasta encontrava-se além do PDF dos padrões funcionais, todas as telas de ajuda que o Ten Alexandre tinha criado. O botão ? de ajuda do sistema não funcionada também por causa disso.
Solução: enviar a pasta com os docs para importar no servidor do CITEx na aplicação ROOT.
