### ISSUE TITLE
Exclusão de requerimentos 

### ISSUE THREAD

**Issue by fabiosampaio12** [SERMIL/portal#130]
Usuários reclamam não conseguir excluir requerimentos.
![deletar requerimento](https://cloud.githubusercontent.com/assets/12251958/9407475/e8c10a7e-47df-11e5-911f-76d552187b44.JPG)

**Comment by wagnerlopes** [comment]
Vou verificar o que está ocorrendo. Como não é essencial, vou deixar com prioridade mais baixa.

**Comment by wagnerlopes** [comment]
Resolvido. Corrigido na versão 5.2.4.
