### ISSUE TITLE
Emissão de relatório de distribuídos 330A e 330b

### ISSUE THREAD

**Issue by fabiosampaio12** [SERMIL/portal#131]
A 6ªRM está necessitando emitir com urgência  o relatório de distribuídos, para apresentar em um processo na justiça e o relatório está sendo emitido em branco. Conforme mensagem anexo. 
![relatorio de distribuidos](https://cloud.githubusercontent.com/assets/12251958/9407808/35f5c890-47e3-11e5-96e3-fe10b12e9228.JPG)

**Comment by wagnerlopes** [comment]
O relatório está vazio porque os cidadãos não estão mais na situação "Distribuídos", ou foram incorporados ou estão no excesso. 
Este é o tipo de relatório que a RM deveria imprimir na época da distribuição (dezembro), depois que a situação evolui não tem mais como emitir do mesmo modo em que estava em dezembro do ano passado.
