### ISSUE TITLE
Leitura de BCC e IAP

### ISSUE THREAD

**Issue by 6975usa** [SERMIL/portal#132]
Varias RM fizeram carga de BCC/IAP com poucos registros e estao perguntando ao @fabiosampaio12  se a carga esta correta.

Pergunto se eh necessario rodar alguma procedure no banco para validar essas cargas de BCC/IAP.
@wagnerlopes   @romulodba

**Comment by romulodba** [comment]
Anselmo,

Amanhã pela manhã visualizo a procedure.

Att,


*Prof. Rômulo Santos*www. <http://www.dominandoti.com.br>do
<http://www.dominandoti.com.br>minandoti.com.br
<http://www.dominandoti.com.br>
*A melhor** p**reparação para concursos na área de tecnologia da
informação.*

Em 27 de agosto de 2015 14:54, Anselmo S Ribeiro <notifications@github.com>
escreveu:

**Comment by fabiosampaio12** [comment]
Informo ainda, que as RM ainda continuam entrando em contato para verificação de arquivos carregados, que ainda não estão disponíveis para consulta. Devido aos testes com a novas leitoras.
