### ISSUE TITLE
Criação de cia territorial 23BC 

### ISSUE THREAD

**Issue by sgtlima** [SERMIL/portal#135]
Solicitado pela 10° região militar a criação de cia territorial 23BC e o QCP devido ao exercicio de mobilização que ocorrerá em novembro de 2015.

**Comment by wagnerlopes** [comment]
@romulodba 
Tem um script SQL no repositorio database que permite criar esses QCP de Cia Gda Ter.
É só criar a OM seguindo a lógica de atribuição de CODOM que começa com 92 ou 93, não me recordo.

**Comment by wagnerlopes** [comment]
Caminho do script:
database/scripts/mob/qcp_cia.sql

Cuidado com o loop que irá dar erro porque as OM ja tem QCP criado.
