### ISSUE TITLE
Data errada no cadastro de eventos

### ISSUE THREAD

**Issue by sgtlima** [SERMIL/portal#136]
Informo-vos que desde ontem (02/09/2015) está ocorrendo um erro na atualização de eventos no SERMIL, pois ao salvar o sistema coloca automaticamente a data do dia e não a data escrita pelo operador.

![erro](https://cloud.githubusercontent.com/assets/14078817/9658259/829bb912-521e-11e5-83b3-2318b6bc28a0.jpg)

**Comment by wagnerlopes** [comment]
Está mesmo colocando a data atual.
Precisa ser corrigido com urgência, tem impacto no cadastramento de FAM que as CSM/JSM estão realizando.
@6975usa  @andremb2211

**Comment by wagnerlopes** [comment]
Problema está na linha 68 da classe https://github.com/SERMIL/portal/blob/next/portal/src/br/mil/eb/sermil/intranet/actions/CidadaoEventoAction.java#L68
onde é mandado colocar a data atual, ao invés da data informada pelo usuário.
Acho que o melhor era colocar im if (data is null) ou eliminar a linha se não for necessária. Não fui eu quem colocou este código. Verifiquem @6975usa @andremb2211

**Comment by andremb2211** [comment]
Problema solucionado.

Validamos o formulário e retiramos a linha de código mencionada foi retirada.

**Comment by wagnerlopes** [comment]
Merge realizado. Sai na versão 5.2.4.
