### ISSUE TITLE
Sitação de JSM Informatizada não esta mudando. 

### ISSUE THREAD

**Issue by sgtlima** [SERMIL/portal#138]
Ao marca na JSM a opção de conexão com a internet e salvar. Não esta ficando a opção salva. Pois ao pesquisar. O campo Infor fica com "N". Como as seguintes imagens abaixo demostram. 
![iamgem 02](https://cloud.githubusercontent.com/assets/14078817/9855941/dba641d6-5ae7-11e5-81fe-54b903a3bc1e.jpg)
![imagem 01](https://cloud.githubusercontent.com/assets/14078817/9855940/dba3fe1c-5ae7-11e5-8487-d1dc264123d1.jpg)

**Comment by wagnerlopes** [comment]
Não é mais para a JSM utilizar o campo Internet. Ele foi desativado. 
Atualmente estamos usando este campo para manter a informação das JSM que estão realizando Alistamento Online no Estado de Sergipe.
Avisem as JSM para não mexer neste campo. @fabiosampaio12 @sgtlima

**Comment by fabiosampaio12** [comment]
Como posso fazer a alteração de JSM não informatizada para JSM informatizada direto na aplicação? Ou essa alteração não está mais disponível na aplicação?

**Comment by wagnerlopes** [comment]
Era pra estar disponivel o campo Informatizada (S/N), esta aparecendo o campo Internet (S/N), acho que tem um erro na tela o campo errado está apagado.
Nesta linha de código:
https://github.com/SERMIL/portal/blob/next/portal/WebContent/jsp/jsm-informacoes.jsp#L65

@6975usa @andremb2211

**Comment by andremb2211** [comment]
Problema Solucionado.

Campo "conexão internet" da jsm foi inibido. Desta forma o campo não será mais exibido para o usuário.
