### ISSUE TITLE
Impressão CDI - Impressora Laser

### ISSUE THREAD

**Issue by fabiosampaio12** [SERMIL/portal#145]
Após diversos testes de impressão de CDI em impressoras laser e jato de tinta, conclui-se que existe a necessidade de readequar os campos no formulário descendo 6mm, para que a impressão fique correta, portanto, diante do exposto e após documentos impressos fora dos campos entregues ao Ten Anselmo, solicito a possibilidade de atender a solicitação.

**Comment by andremb2211** [comment]
De acordo com a orientação do tenente Anselmo não iremos realizar tratamento para a situação descrita acima.
