### ISSUE TITLE
REL 8108 - Certidão de Situação Militar - pouco espaco

### ISSUE THREAD

**Issue by 6975usa** [SERMIL/portal#148]
O Maj Bartz relatou que 3ª RM solicitou  o aumento do campo "Períodos" para inclusao de Certidao de Situacao Militar. 
Solicitou a possibilidade de transforma-lo em textarea.
Atualmente o campo esta limitado a 50 caracteres. Ele solicita que seja ilimitado.

![certificado cadastro](https://cloud.githubusercontent.com/assets/6667748/9991902/98fe384a-6044-11e5-85d6-ef027efa8148.png)

**Comment by wagnerlopes** [comment]
Estudar se é possível colocar na página, acho mais viável somente aumentar o campo com cuidado pois pode não haver espaço físico na página e ficar o layout confuso. Tem que ver se a coluna na tabela suporta a string a ser armazenada.
