### ISSUE TITLE
Solicitação de Alteração de Tributação 

### ISSUE THREAD

**Issue by fabiosampaio12** [SERMIL/portal#15]
As Regiões Militares estão com dificuldade no lançamento de solicitações de alteração de tributação, ou seja, no menu RM/TRIBUTAÇÃO, ao solicitar uma alteração na tributação o sistema está apresentando a mensagem de erro anexa. 
![tributacao](https://cloud.githubusercontent.com/assets/12251958/7524219/cbc9a270-f4d6-11e4-9a18-ae01edbddf00.jpg)
![tributa1](https://cloud.githubusercontent.com/assets/12251958/7524222/d48eebae-f4d6-11e4-8780-76335a05caf5.JPG)

**Comment by wagnerlopes** [comment]
Alteração de tributação encerra em 30 de abril o prazo para as RM informarem o sistema.
Já foi rodado o programa que executa a alteração da tributação/vinculação de JSM.
