### ISSUE TITLE
Relatório 8020 - Aptos distribuição

### ISSUE THREAD

**Issue by fabiosampaio12** [SERMIL/portal#164]
Informo que o relatório 8020 - Aptos a distribuição referente ao ano 2014 da 12ª RM está apresentando erro, ou seja, está saindo em branco. Enquanto as demais regiões está sendo impresso normalmente. Peço a gentileza de verificar o que está ocorrrendo. 

![relatorio 8020 - aptos](https://cloud.githubusercontent.com/assets/12251958/10282058/0590a578-6b4f-11e5-9765-18a86ac458d8.jpg)

**Comment by wagnerlopes** [comment]
@fabiosampaio12 Este relatório está sendo preparado para a distribuição 2015, os dados de 2014 são perdidos. Cada RM deveria imprimir o seu e guardar quando ocorre o evento. Estamos limpando diversas tabelas visando a proxima distribuição. Lembre as Rm desse fato.
