### ISSUE TITLE
Atualização do Relatório 8009 -  Estatisticas BCC/IAP

### ISSUE THREAD

**Issue by fabiosampaio12** [SERMIL/portal#166]
Algumas RM estão necessitando visualizar o relatório 8009, para certificar que as cargas de BCC/IAP estão corretas. Solicito a possibilidade de rodar script no banco de dados para atualizar estatística da cargas.

**Comment by wagnerlopes** [comment]
Atualizado.

**Comment by wagnerlopes** [comment]
@fabiosampaio12
