### ISSUE TITLE
Alteração de datas na Carta do EXAR

### ISSUE THREAD

**Issue by fabiosampaio12** [SERMIL/portal#170]
Solicito verificar e  fazer a alteração do período de apresentação do EXAR na carta do EXAR, através do menu: OM/ Mobilização/Relatórios do EXAR/REL 8058

Alteração de datas, conforme descrito entre parênteses abaixo:

EXERCÍCIO DE APRESENTAÇÃO DA RESERVA
CARTA DE CHAMADA
De acordo com o Regulamento da Lei do Serviço Militar Decreto-Lei N. 57.654, de 20 de janeiro
de 1966, Art. 202, Vossa Senhoria deverá comparecer à Organização Militar onde foi licenciado (a), no período de (09 a 16 de dezembro de 2015), para fins de realização de Exercício de Apresentação da Reserva.
Caso deseje, V. S.ª poderá realizar sua apresentação pelo EXARNET por intermédio do site:
www.exarnet.eb.mil.br, no período de (1º de dezembro de 2015 a 31 de janeiro de 2016).

**Comment by wagnerlopes** [comment]
Está corrigido, sairá na versão 5.2.5 em 31/10/2015.
