### ISSUE TITLE
Boleto CEF

### ISSUE THREAD

**Issue by fabiosampaio12** [SERMIL/portal#171]
Informo que na data de hoje 13/10/2015 em reunião entre o Ministério da Defesa e a Caixa Econômica Federal foi detectado que o layout de emissão das taxas e multas militares, está em desacordo com Layout da CEF para emissão de boletos. Foi enviado via e-mail para este suporte o Layout  correto que deverá ser seguido para emissão desses boletos. 
Layout enviado para os seguintes e-mails
anselmoribeiro@dsm.eb.mil.br , romulo@dsm.eb.mil.br e wagner.luis.alopes@gmail.com

**Comment by wagnerlopes** [comment]
Nos documentos anexos não consta nada sobre Layout incorreto do Boleto de Taxas/Multas.
Consta os layoutS DE ARQUIVOS para troca de informações entre a CEF e os clientes (o SERMIL por exemplo), visando informar toda a movimentação financeira realizada em determinado período.
Acho que o pessoal do MD não entendeu direito do que se tratava.
Os Boletos implementados no sistema seguem o mesmo padrão que está em uso há anos sendo impresso pela gráfica, então estão errados há 40 anos os formulários impressos?

**Comment by wagnerlopes** [comment]
@fabiosampaio12 : Preciso de retorno sobre esta situação que descrevi acima.

**Comment by wagnerlopes** [comment]
Arquivos recebidos da CEF:

[COBRANÇA.pdf](https://github.com/SERMIL/portal/files/14258/COBRANCA.pdf)

[COBRANÇA II.pdf](https://github.com/SERMIL/portal/files/14259/COBRANCA.II.pdf)

**Comment by fabiosampaio12** [comment]
Entrei em contato com o Ministério da Defesa para me certificar sobre as alterações que porventura deveriam acontecer na troca de arquivos  e possíveis alterações no layout da emissão dos boletos de taxas e multas da Caixa Econômica, porém quem está ciente do assunto é o Cel Sampaio e ele não está no Ministério, ficou de dar retorno na sexta feira 16/10/2015. Estou no aguardo.
 @wagnerlopes

**Comment by fabiosampaio12** [comment]
Em contato com Cel Sampaio do MD ele informou que atendendo uma solicitação da DSM ele foi verificar junto à CEF e  ECT uma maneira de identificar o cidadão que está pagando as taxas e multas. De acordo com a CEF o convênio do MD para arrecadação não possui arquivo de retorno informando o pagamento, portanto, será necessário se adequar a este novo layout (arquivo disponibilizado) para que receba o retorno de pagamento. Enquanto para ECT os boletos enviados para testes, tanto para taxa quanto para multa o campo de identificação do cidadão esta indo com mesmo número, portanto, deverá ser alterado para que o sistema possa retornar o número de identificação válido. O Cel Sampaio está verificando na gerência da ECT a possibilidade de envio de layout da ECT para facilitar a equipe na adequação.

**Comment by fabiosampaio12** [comment]
A ECT informou que o manual constante no link abaixo é de acesso público. Nele é possível montar o código de barras com as especificações necessárias para servir de subsidio para  o desenvolvedor do sistema para identificação do cidadão que fez o pagamento.

http://www.febraban.org.br/7Rof7SWg6qmyvwJcFwF7I0aSDf9jyV/sitefebraban/Codbar4-v28052004.pdf

**Comment by wagnerlopes** [comment]
O boleto foi montado seguindo exatamente essa especificação da Febraban.
Acho que o pessoal está comendo bola, e não anda vendo direito as coisas.
