### ISSUE TITLE
Erro na atualização do cidadão, na aba informações -> Militar

### ISSUE THREAD

**Issue by sgtlima** [SERMIL/portal#173]
Ao pesquisar o cidadão, informo numero de RA. Após ir na aba informações -> Militar. Ao fazer alguma alteração no mesmo acontece o erro, como na imagem abaixo. (O erro abaixo aconteceu na alteração, de posto ou graduação). 
![erro](https://cloud.githubusercontent.com/assets/14078817/10483244/a917dc6e-7254-11e5-8047-20bd5b8ea68d.jpg)

**Comment by wagnerlopes** [comment]
Não encontrei nenhum problema aparente, o erro deve ter ocorrido em conexão lenta da Internet onde o usuário não espera preencher a lista dinâmica com códigos de OM, QCP e Frações do QCP que geralmente demoram em situações de conexão lenta, ou com o servidor sobrecarregado.
Vamos monitorar e ver se não aparece outro motivo para este erro.
