### ISSUE TITLE
Relatorios da 10 RM gerandos em branco. 

### ISSUE THREAD

**Issue by sgtlima** [SERMIL/portal#174]
Os relatórios apenas da 10 RM estão sendo gerados em branco. Testei um por 1, e os mesmos são os unicos saindo em branco. O mesmos não estão conseguindo fazer a autoria das CS por causa disto. Já com as outras RM esta tudo normal. Segue abaixo a lista de relatórios que estão sendo gerados em branco: 

a. Relatório de Processamento das cargas pela CS - 8102A

 b. REL 8017 - Aptos na Seleção (CS/JSM)

 c. REL 8080 - Faltas na Seleção

 d. REL 8002 - Mapa Controle de Seleção Geral

 e. REL 8007 - Mapa Controle de Seleção Especial

 f. REL 8019 - Relatório Final de Seleção
  
 g. REL 8008 - Estatísticas de BCC/IAP (Leitura)

 h. REL 8003 - Parâmetros da Distribuição

 i. REL 8022 - Boletins de Necessidade

 j. REL 8023 - Dispensas da Distribuição

 k. REL 8050 - Distribuição Forçada

 l. REL 8102 - Arquivos de FS (por CS)

**Comment by wagnerlopes** [comment]
Detectei o problema no código-fonte da página HTML dos relatórios, onde na lista html está sendo enviado o seguinte comando **``<option value="0">10&ordf; RM``** onde ao invés de enviar RM=10 para o rela'torio está enviando RM=0 o que impede de gerar os relatórios da 10 RM.
Isso deve ter ocorrido por alguma substituição em lote de comandos usando o Eclipse.
Desenvolvrdores @aryene @6975usa @andremb2211 cuidado ao fazer substituição de código automática!
Vai ser corrigido na versão 5.2.5 prevista para 31/10/2015. @sgtlima @fabiosampaio12 avisar se leram este post!

**Comment by wagnerlopes** [comment]
Resolvido na versão 5.2.5
