### ISSUE TITLE
Erro na geração do CDI gerado para atender os BRE. 

### ISSUE THREAD

**Issue by sgtlima** [SERMIL/portal#178]
Quando o cidadão não possui certificado lançando no sistema, e já possui o Evento cadastrado como excesso de contingente. Ao cadastrar o certificado, na aba certificados.
E Depois fazer a emissão do CDI, o mesmo não puxa da data de dispensa do evento que já estava cadastrado, e sim puxa da data de confecção do CDI.
Foi feito um teste no RA: 999003987164 - REGIS OKUDA YAMAGUISHI.
O mesmo foi dispensado no dia 08/02/2013 E o CDI gerado esta puxando a data do certificado dia 13/10/2015

![cdi](https://cloud.githubusercontent.com/assets/14078817/10583757/9efae06a-766d-11e5-9619-3264966786ee.jpg)

**Comment by wagnerlopes** [comment]
Precisa confirmar qual a regra de negócio está valendo.
Parece que há  um conflito entre o que é feito em um lugar e em outros.
CDI com data atual ou data da dispensa?
