### ISSUE TITLE
Erro no Alistamento via Portal

### ISSUE THREAD

**Issue by wagnerlopes** [SERMIL/portal#18]
Verificar se está ocorrendo problema no alistamento do Portal e duplicando RA com o alistamento via SERMILWEB.

**Comment by wagnerlopes** [comment]
Localizei um problema em CidadaoServico.alistar, que estava tentando deletar o pre_alistamento que não existe mais nesta situação.

**Comment by 6975usa** [comment]
uau
isso é grave.
Um Maj da CSM de Sergipe me ligou dizendo que alguns alistamentos online estao se perdendo, ou seja, o cidadao chega la com Recibo do alistamento online mas eles nao conseguem achar o alistamento no Sermil.
Com o RA que o cidadao traz, eles acham outro cidadao.

![190034209105](https://cloud.githubusercontent.com/assets/6667748/7573820/f9aa1ffa-f7fe-11e4-8b51-a49990ea32f5.jpg)

**Comment by wagnerlopes** [comment]
Estou fazendo uma revisão no código, vou desativar o cache JPA da entidade RA_MESTRE.
Ontem fiz uma atuliazação do sermilweb na organização.

**Comment by wagnerlopes** [comment]
1o. alistamento: 190034209105 - HUGO JUCUNDO BISPO DA SILVA
Foi realizado via Portal pela JSM 19/003 
Em doc sistema temos: Tipo: 1 Data: 27/04/2015 Svr: 10019003888 Tar: 0 Doc: 0 - FAMCO

2o. alistamento com esmo RA foi realizado pelo cidadão via sermilweb e foi sobrescrito quando aconteceu o alistamento via Portal acima.

Uma solução momentânea, até ser localizado o problema, é retirar do ar o link do alistamento no Portal, assim podemos monitorar o alistamento online sem que haja interferência do Portal.

Temos que lembrar que são duas aplicações trabalhando em PARALELO, há a questão do cache da JPA que pode estar atrapalhando.

**Comment by wagnerlopes** [comment]
# Importante! @6975usa 

Colocar no Portal:

```
<prop key="eclipselink.cache.shared.RaMestre">false</prop>
```

**Comment by wagnerlopes** [comment]
# Importante! @6975usa 

Colocar:
```
<prop key="eclipselink.cache.shared.RaMestre">false</prop>
```

**Comment by 6975usa** [comment]
Ok

**Comment by wagnerlopes** [comment]
O serviço de Alistamento via Portal foi retirado do ar para evitar conflito com o Alistamento Online do SERMILWEB.
