### ISSUE TITLE
Relatorio 8072 saindo em branco

### ISSUE THREAD

**Issue by sgtlima** [SERMIL/portal#182]
Foi verificado que o relatório 8072 - com a opção sem Destino, esta saindo em branco. Sendo gerado como null. Testado pela OM que acusou o problema (1rm -> CMDO 1rm) gerado em branco e testado também com diversas RM e OM diferentes também gerado em branco. 
![rel 8078 - oficiais r-2](https://cloud.githubusercontent.com/assets/14078817/10636149/6011ff94-77dc-11e5-9da9-94c1f6b5eec6.jpg)
![relatorio 8078](https://cloud.githubusercontent.com/assets/14078817/10636191/c55f1ada-77dc-11e5-82c8-d8f803bb2af1.jpg)

**Comment by wagnerlopes** [comment]
Solução: rodar a stored procedure no banco de dados.

comando no Oracle SQLDeveloper: exec ssm_estat.lista_carencia_rh
