### ISSUE TITLE
Solicitação para incluir Campos no Menu HABILITAÇÃO

### ISSUE THREAD

**Issue by sgtlima** [SERMIL/portal#184]
Solicito a possibilidade de que seja acrescentado no SERMILMOBWEB, no campo HABILITAÇÃO, o ESTÁGIO DE OPERAÇÃO DO SISTEMA ASTROS PARA OFICIAIS e o ESTÁGIO DE OPERAÇÃO DO SISTEMA ASTROS PARA SARGENTOS, pois não há no referido Sistema.

O 6º GMF é a OM que habilita o universo de Of/Sgt no Sistema Astros. Anualmente são formados entre 40/50 Of/Sgt. Por sinal, é a única OM com essa incumbência. Então, se faz necessário que o referido estágio esteja no SERMIL para o devido cadastro.

**Comment by wagnerlopes** [comment]
Tabela de habilitação pertence ao EBCORP, será necessário carregar as atualizações quanto for feito a integração EBCORP - SERMIL.
