### ISSUE TITLE
Erro no Relatorio Mobilização EXAR (Pesquisa da Reserva)

### ISSUE THREAD

**Issue by sgtlima** [SERMIL/portal#185]
Informo erro no relatório (OM -> Pesquisa da Reserva)
Após informar todos os dados e clicar no botão PESQUISAR, os campos preenchidos em Municípios ZERAM. Sem trazer resultado nenhum. Como na imagem abaixo. 
![relatorio erro](https://cloud.githubusercontent.com/assets/14078817/10788691/4e25daec-7d60-11e5-92d4-e740ac426398.jpg)

**Comment by andremb2211** [comment]
Já estou verificando.
