### ISSUE TITLE
Erro ao abrir pagina Relatórios -> Certificados. 

### ISSUE THREAD

**Issue by sgtlima** [SERMIL/portal#193]
Ao segui o caminho: Relatórios -> Certificados, o sistema não abre pagina. Como segue na imagem abaixo.
![erro certificados](https://cloud.githubusercontent.com/assets/14078817/11097427/8501ff24-8886-11e5-871a-31d0d63061a4.jpg)

**Comment by wagnerlopes** [comment]
Retornando erro HTTP 500 - Internal Error

Causa: Erro na compilação da página JSP.

Verificar quem modificou a página da última vez, algum bug foi introduzido nas tags JSP que impede da página ser compilada em tempo de execução.

**Comment by andremb2211** [comment]
Erro no Relatórios(Certificados)

Realizado ajuste na linha 49 da pagina rel - certificados.jsp

O campo required estava vazio.

**Comment by 6975usa** [comment]
@andremb2211 Corrigiu este erro.
Bom trabalho, @andremb2211

**Comment by sgtlima** [comment]
Informo que tenho recebido, varias ligações de varias regiões militares com a necessidade de gerar este relatório devido ao desligamento de vários militares agora no final do ano, militares temporários, contritos, alunos do NPOR E CPOR. Inclusive os militares indo para reserva. Que necessitam do certificado.
