### ISSUE TITLE
Erro no Relatorio Carta Chamada para o EXAR (8058)

### ISSUE THREAD

**Issue by sgtlima** [SERMIL/portal#196]
Caminho do relatório: OM-> Relatório do EXAR. 
![erro exar1](https://cloud.githubusercontent.com/assets/14078817/11211646/129f9266-8d18-11e5-9e89-bb4da59fcd25.jpg)
![erro exar2](https://cloud.githubusercontent.com/assets/14078817/11211645/129abd68-8d18-11e5-8966-9b2cc88be0a2.jpg)

Ao gerar a carta de chama do exar, o mesmo não esta saindo a cidade. Como no exemplo na imagem só aparecer RS, a cidade que é Pelotas não esta aparecendo.

**Comment by wagnerlopes** [comment]
Pede pro usuário configurar o endereço da OM no menu <OM> > Informaçoes da OM, lá tem uma tela onde são colocados os dados referentes ao cabeçalho que aparece na Carta-chamada.

**Comment by sgtlima** [comment]
O questionamento do usuário foi em relação ao endereço quem vai receber a carta de chamada. No exemplo a imagem que coloquei, em cima do CEP só esta o "RS".

**Comment by sgtlima** [comment]
Venho recebendo diversas ligações sobre o erro descrito, segue uma nova imagem detalhando mais sobre o problema. 
![carta de chamada](https://cloud.githubusercontent.com/assets/14078817/11441093/c2702442-94ef-11e5-99c0-bc4b7ae41485.jpg)

**Comment by wagnerlopes** [comment]
Corrigido. Sai a versao 5.2.6
