### ISSUE TITLE
Mudança de perfil emergenciais. 

### ISSUE THREAD

**Issue by sgtlima** [SERMIL/portal#197]
Solicito a mudança dos usuários que estão com o perfil de JSM(07) e P/G = FC, para JSM(07) e DEL SM(10) devido aos erros no sistema para alistamento, com o usuários que estão somente com o perfil de JSM(07).

**Comment by wagnerlopes** [comment]
Feito, todos os usuarios com perfil JSM estão com perfil DELSM.
