### ISSUE TITLE
OM inserido dois Bol Nec para o mesmo ano

### ISSUE THREAD

**Issue by 6975usa** [SERMIL/portal#200]
O Cap Alberto mostrou que uma OM ta podendo inserir dois BolNec para o mesmo ano  conforme figura abaixo;

![29bibbolnec2014](https://cloud.githubusercontent.com/assets/6667748/11245686/1a20979a-8dfb-11e5-86be-7a704b44c8e0.png)

**Comment by wagnerlopes** [comment]
Mas pode mesmo, é comum certas OM inserirem mais de um bol nec, isso para
poder participar demais de um GD na distribuição.
Em 18/11/2015 1:49 PM, "Anselmo S Ribeiro" <notifications@github.com>
escreveu:
