### ISSUE TITLE
Inconsistência/erro no SERMIL

### ISSUE THREAD

**Issue by sgtlima** [SERMIL/portal#201]
Tenho recebido varias ligações de varias localidade diferente, informando um erro ao salvar, alterar qualquer dado no sistema. 
Segue abaixo a tela do erro. 
![erro1](https://cloud.githubusercontent.com/assets/14078817/11337466/630079d0-91d4-11e5-8c16-201fd25ba956.jpg)

**Comment by wagnerlopes** [comment]
@6975usa retornando o SERMILWEB para o servidor físico e abandonando a virtualização executada no CITEx na semana passada.

**Comment by wagnerlopes** [comment]
Informa o ID sempre que o erro ocorrer ao suporte técnico.
