### ISSUE TITLE
Padrões Funcionais

### ISSUE THREAD

**Issue by wagnerlopes** [SERMIL/portal#206]
Filtrar a lista de padrões que aparece na tela de preenchimento de BolNec para não aparecer os padrões:

- A99; B99; C99; E99; G99; M99; Z99
- F01; F02; F03

Estes padrões são usados apenas pelo programa de distribuição, não devem ser atribuídos pelas OM nos boletins de necessidade.

**Comment by andremb2211** [comment]
Foi criado filtro conforme solicitado.
