### ISSUE TITLE
Alistamento online - bloquear campo Data de Nascimento

### ISSUE THREAD

**Issue by 6975usa** [SERMIL/portal#215]
Alistamento Online.
Gostaria de saber se, assim como acontece aos campos "Nome" e "Nome da Mae", o campo "Data de Nascimento" deve ser bloqueado, considerando que esse dado vem da validacao do CPF na pagina anterior. 
![0001](https://cloud.githubusercontent.com/assets/6667748/12301999/20402d4e-ba0a-11e5-855a-dd1425aa5928.png)

**Comment by wagnerlopes** [comment]
Deixei assim temporariamente para poder realizar alguns testes onde tinha que mudar a idade.
