### ISSUE TITLE
Alistamento Online - Banner com informacao divergente

### ISSUE THREAD

**Issue by 6975usa** [SERMIL/portal#216]
No Alistamento Online, um Banner diz que é necessario ter Titulo de Eleitor.
No entanto as regras de negocio e o formulario de alistamento nao exigem Titulo de Eleitor.
![0002](https://cloud.githubusercontent.com/assets/6667748/12302437/49376454-ba0c-11e5-9627-0441a71a633c.png)

**Comment by wagnerlopes** [comment]
Realmente não precisa de Titulo de Eleitor, foi invenção do Alexandre. Tem que mudar o banner.

**Comment by andremb2211** [comment]
Foi retirado o banner com a informação divergente.
