### ISSUE TITLE
Erro: Não aparece Numero do RA e Nome em Tela no SERMIL

### ISSUE THREAD

**Issue by sgtlima** [SERMIL/portal#219]
![erro1](https://cloud.githubusercontent.com/assets/14078817/12396066/87393a32-bdec-11e5-954d-2eba636a4887.jpg)

Tela: 
OM -> Incorporação. 
Como mostra na imagem em vermelho não aparece os dados do Cidadão.

**Comment by wagnerlopes** [comment]
Estou corrigindo a tela, action e o serviço. Também vou implementar algumas melhorias, essa funcionalidade foi definida a 5 anos, precisa de uma reengenharia.

**Comment by wagnerlopes** [comment]
Correção efetuada.
