### ISSUE TITLE
Alistado online no exterior nao consegue acompanhar alistamento

### ISSUE THREAD

**Issue by 6975usa** [SERMIL/portal#220]
![image](https://cloud.githubusercontent.com/assets/6667748/12429595/5b143ede-bed2-11e5-9fea-c249b4c76b16.png)

**Comment by wagnerlopes** [comment]
Substituí na versão 5.2.7 a situaçao militar para 1(ALISTADO) e 3(DISPENSADO), quero ver se resolve o problema.
