### ISSUE TITLE
Erro no relatório 8108 - Certidão de Situação Militar 

### ISSUE THREAD

**Issue by sgtlima** [SERMIL/portal#228]
Foi recebido e testado, a situação deste militar que esta gerando a certidão em branco. 
Segue abaixo os exemplos. 
![erro relatorio - certidao de situacao militar 01](https://cloud.githubusercontent.com/assets/14078817/12588589/784c1d78-c440-11e5-9d31-a4b1ea19528b.jpg)
![erro relatorio - certidao de situacao militar](https://cloud.githubusercontent.com/assets/14078817/12588590/784f9462-c440-11e5-8886-798f553ba68b.jpg)

**Comment by andremb2211** [comment]
Alterado SQL de consulta do relatório no banco de dados.

**Comment by 6975usa** [comment]
O Sgt Borges resolveu esse issue.
