### ISSUE TITLE
Campo RG

### ISSUE THREAD

**Issue by fabiosampaio12** [SERMIL/portal#230]
O PRM de São Luis - MA está reclamando que o campo RG (10 dígitos) não comporta o número do RG do estado do Maranhão que possui 13 dígitos, portanto, 3 dígitos a mais do que é disponiblizado na aplicação. Favor verificar e caso seja possível fazer as devidas alterações.

**Comment by wagnerlopes** [comment]
Já corrigi o formulário de alistamento para receber ate 100 caracteres no numero do doc.
