### ISSUE TITLE
Alterar a grafia de texto

### ISSUE THREAD

**Issue by fabiosampaio12** [SERMIL/portal#24]
Peço a gentileza de fazer alteração no texto da tela referente ao alistamento ONLINE

https://www.sermilweb.eb.mil.br/aol/inicio.action;jsessionid=6C582BB768A60BC54F351D61BEC63DC4

GRAFIA CORRETA (com as devidas correções solicitadas)
O Certificado de Alistamento Militar (CAM) somente será emitido na Junta de Serviço Militar, solicite-o, caso seja necessário comprovar o alistamento junto a algum órgão público ou empresa privada.

GRAFIA ERRADA 
![correcao](https://cloud.githubusercontent.com/assets/12251958/7653080/7e900530-fae9-11e4-97cb-f489581126ba.jpg)

**Comment by wagnerlopes** [comment]
Alterado. Sai na próxima versão (5.1.15)
