### ISSUE TITLE
Alteração no Texto

### ISSUE THREAD

**Issue by fabiosampaio12** [SERMIL/portal#25]
https://www.sermilweb.eb.mil.br/aol/inicio.action;jsessionid=6C582BB768A60BC54F351D61BEC63DC4

Acrescentar na grafia do texto o documento CPF

Para realizar o alistamento será necessária a utilização dos dados de um dos seguintes documentos:

    Certidão de Nascimento;
    Certidão de Casamento;
    Nacionalização; ou
    Registro Geral (Identidade).
    CPF
   
![correcao](https://cloud.githubusercontent.com/assets/12251958/7653190/295af696-faea-11e4-990a-e601a72162f7.jpg)
 CPF

**Comment by wagnerlopes** [comment]
Incluído.
