### ISSUE TITLE
Erro: Ano de alistamento saindo em branco no CAM

### ISSUE THREAD

**Issue by sgtlima** [SERMIL/portal#255]
Ao imprimir o CAM o ano de alistamento esta saindo em BRANCO. Como mostra na imagem abaixo. 
RA do CAM da imagem: 991572013076
![cam erro](https://cloud.githubusercontent.com/assets/14078817/13115658/cd4af506-d57f-11e5-9ca0-e549fb118292.jpg)

**Comment by wagnerlopes** [comment]
Consertado na versão 5.3.1
