### ISSUE TITLE
Relatórios de Alistamento - MRE

### ISSUE THREAD

**Issue by fabiosampaio12** [SERMIL/portal#26]
No menu RELATÓRIOS/ALISTAMENTO os relatórios 8103 - Alistados pela Internet e 8006MRE estão saindo em branco, ou seja, sem dados. Favor verificar a necessidade de rodar algum script para que esses dados sejam atualiados. 
![relatorios](https://cloud.githubusercontent.com/assets/12251958/7681478/fd738a34-fd46-11e4-8ace-001e4a0a5202.jpg)

**Comment by wagnerlopes** [comment]
Provavelmente é porque ele foi pensado para funcionar com o **Pré-alistamento**, que não existe mais. A query deve estar falhando com o **Alistamento Online**. A condição deve estar errada no relatório, tem que ser alterada.

**Comment by wagnerlopes** [comment]
Parâmetros incorretos informados pela página JSP.
Alterei na página e no relatório jasper pra funcionar corretamente.
Sai na próxima versão.
