### ISSUE TITLE
Menu CS

### ISSUE THREAD

**Issue by fabiosampaio12** [SERMIL/portal#262]
Estou fazendo tutorial para envio as RM sobre o novo meu SERMIL (CS). O menu CS/Agenda está voltado para CS permanente de Salvador,  ou seja, não trás filtros para delimitar a pesquisa. Quando fazemos a pesquisa aparece os dados dos cidadãos de Salvador. Esse menu vai ser alterado para filtrar os dados das demais CS do Brasil, portanto, possivelmente ainda não está completo. Estou certo? Haverá muitas alterações ou posso continuar fazendo o tutorial?
![cs](https://cloud.githubusercontent.com/assets/12251958/13461624/6a292c58-e061-11e5-89a1-3df2227dee65.JPG)

**Comment by wagnerlopes** [comment]
Sim, essa tela esta disponivel apenas pra CS de Salvador funcionar. É
quebra-galho mesmo.
Pro resto do Brasil terá que ser modificado.
Mas as CS irão funcionar só depois de julho, então estamos tranquilos por
enquanto.


Em 2 de março de 2016 10:28, Ten Sampaio <notifications@github.com>
escreveu:
