### ISSUE TITLE
Cadastro de OM/Informações

### ISSUE THREAD

**Issue by fabiosampaio12** [SERMIL/portal#265]
O usuário dos sistema ao tentar cadastrar/atualizar os dados da OM através do Menu OM/INFORMAÇÔES está aparecendo o erro anexo 
![om informacoes](https://cloud.githubusercontent.com/assets/12251958/13570702/9789e7e6-e44e-11e5-9087-d4cba72007fd.JPG)

**Comment by wagnerlopes** [comment]
OK, vou verificar que esta tela foi atualizada por causa da assinatura do responsavel da OM, algo pode ter ficado incorreto.

**Comment by wagnerlopes** [comment]
Fiz a correção da issue #265, mas coloquei para sair na versão 5.3.2
