### ISSUE TITLE
Reimpressão de CAM - Ano Alistamento 

### ISSUE THREAD

**Issue by fabiosampaio12** [SERMIL/portal#27]
A reimpressão do CAM na impressora laser está apresentando erro, ou seja,  o ano de alistamento não está sendo impresso, porém, o problema só ocorre com reimpressão, a primeira impressão do documento no ato do alistamento está correta.

**Comment by 6975usa** [comment]
Ten Sampaio 
Solicito indicar a sequencia de menus para chegar ate a impressao do CAM

**Comment by fabiosampaio12** [comment]
Atraves do Menu CIDADÃO/PESQUISAR opção IMPRIMIR Certificado de Alistamento Militar,  porém, o cidadão deverá estar com a situação militar ALISTADO.

**Comment by 6975usa** [comment]
Resolvido. 
O Ten Sampaio e eu testamos o funcionamento do CAM o funcionou perfeito.
Mas quanto aos relatorios jasper eu nunca tenho muita certeza. 
Caso nao esteja resolvido realmente solicito que nao seja aberto outro issue, mas que esse issue seja reaberto.

**Comment by 6975usa** [comment]
Reabri porque o usuario continua dizendo que o ano não é impresso no CAM.
Primeira impressao imprime o ano correto do alistamento.
Segunda impressao imprime ano em branco.

**Comment by fabiosampaio12** [comment]
Informo ainda, que após a atualização versão 5.1.16, o ano de nascimento também não está saindo na impressão.

**Comment by wagnerlopes** [comment]
Foi alterado na versão 5.1.17, terá que ser testado para ver se está correto.
