### ISSUE TITLE
Boleto CEF e ECT

### ISSUE THREAD

**Issue by fabiosampaio12** [SERMIL/portal#270]
Com advento da emissão do boleto da CEF e ECT através do SERMIL  a DSM não solicitou a gráfica a confeccção de impressos de taxas e multas, portanto, estão cobrando o retorno da emissão através do sistema, pois os quantitativos que tinham nas JSM acabaram . Existe previsão do retorno da emissão dos mesmos através do SERMIL? 
![boletos](https://cloud.githubusercontent.com/assets/12251958/13701849/50281df0-e769-11e5-8136-aea7851fa0ba.JPG)

**Comment by wagnerlopes** [comment]
A emissão está apenas escondida no menu, a DSM precisa autorizar a emissão atraves do Portal.
Todas as vezes que eu disponibilizei alguem pediu pra tirar do ar por algum motivo.
Você pode chamar a tela de emissão assim:
**Chama no menu a emissão de guia, na URL vai aparecer gru.action troca para boleto.action que aparece novamente a tela.**
Eu só vou ativar novamente depois que a DSM autorizar e verificar junto a CEF/Correio que as guias serão aceitas.
