### ISSUE TITLE
Relatório saindo em branco (8030)

### ISSUE THREAD

**Issue by sgtlima** [SERMIL/portal#271]
Relatório -> Incorporação -> REL 8030 - Controle de Incorporação
O mesmo quando gerando sai em branco.

**Comment by aryene** [comment]
Estou analisando

**Comment by wagnerlopes** [comment]
Verifique o que esta ocorrendo @aryene

**Comment by aryene** [comment]
Boa tarde,
o relatório 8030 na base de dados dele tem 3 parâmetros para fazer a consultar
   ANO
   RM
   CODOM 

Já na JSP só tem RM e ANO 

Como faço para colocar na jsp a consultar  do CODOM  ????
