### ISSUE TITLE
Liberação usuário em lote

### ISSUE THREAD

**Issue by fabiosampaio12** [SERMIL/portal#272]
Ao tentar fazer desbloqueio de 6 usuários através da liberação em lote, o sistema está acusando que não espaço suficiente.
![liberacao usuario](https://cloud.githubusercontent.com/assets/12251958/13918691/ab546b26-ef47-11e5-8ad0-e46309e2e861.JPG)

**Comment by wagnerlopes** [comment]
Geralmente este tipo de erro indica problema no servidor.
Pede pro Romulo verificar se o servidor não perdeu o storage onde está gravando os dados.
@romulodba @fabiosampaio12
