### ISSUE TITLE
Emissão de CDI

### ISSUE THREAD

**Issue by fabiosampaio12** [SERMIL/portal#274]
Informo que a emissão de CDI diretamente pelo SERMIL está com problema na data de dispensa do cidadão que não está puxando do evento que gerou a dispensa. Está sendo impresso a data de emissão, ou seja, a data que está sendo emitido o documento e não a data do excesso ou dispensa.

**Comment by wagnerlopes** [comment]
Verifique o que esta ocorrendo @andremb2211

**Comment by andremb2211** [comment]
Estou verificando.

**Comment by andremb2211** [comment]
Estou verificando.
