### ISSUE TITLE
Atualização do valor da Multa Mínima

### ISSUE THREAD

**Issue by fabiosampaio12** [SERMIL/portal#277]
Em virtude da alteração ref. ao trimestre a partir de 1º de Abr 16 o valor da Multa Mínima passou a ser de R$ 3,81 (três reais e oitenta e um centavos), esse valor é válido para os meses de Abr, Mai e Jun 16, portanto, para que o cidadão que faz o alistamento ONLINE consiga emitir o valor correto se faz necessário a alteração no banco de dados do SERMIL.

**Comment by andremb2211** [comment]
Alteração realizada!

Conforme vimos @fabiosampaio12  atualizamos outros campos que também estavam com valores incorretos.

**Comment by 6975usa** [comment]
Bom trabalho, Borges
