### ISSUE TITLE
Solicitação de exclusão de Evento 

### ISSUE THREAD

**Issue by sgtlima** [SERMIL/portal#285]
Solicito a exclusão do evento: excesso de contingente, pelo banco de dados. Pois o mesmo não esta sendo possível excluir pelo sistema. Afim da 5º RM atualizar o cadastro do mesmos. 

RA 150913254127 - Gabriel Torres Lingiardi
RA 150014507407 - Filipe Martinez Santos
RA 160842286108 - Flavio José Medeiros Martins Junior
RA 160842285860 - Gustavo de Oliveira

**Comment by andremb2211** [comment]
Cel @wagnerlopes 

Posso realizar a exclusão dos eventos acima?

Preciso analisar o codigo e analisar o por que nao estão conseguindo excluir?

Pois ao tentar excluir pela aplicação não apresenta erro porem ao consultar novamente, o evento apresenta novamente.

Aguardo,

**Comment by wagnerlopes** [comment]
Eu vou olhar, isso envolve o mapeamento da JPA e suas configurações. Como mexi em alguns pontos do modelo na última atualização, pode ter gerado um bug nessa entidade.
Voces podem testar pra mim se as outras entidades, ex. certificados, documentos, etc. da ficha do cidadão também estão apresentando o problema na exclusão.

**Comment by andremb2211** [comment]
@sgtlima poderia nos informar se ocorre também o erro conforme testes citados pelo Cel?

**Comment by wagnerlopes** [comment]
Erro no mapeamento de entidades da JPA foi encontrado nas classes CidEvento, CidCertificado e CidExar. O mapeamento OneToMany foi corrijido e voltou a funcionar a opção de salvar cidadão e suas entidades agregadas.
Estou colocando atualização no ar no final do expediente.
