### ISSUE TITLE
Emissão de GRU

### ISSUE THREAD

**Issue by fabiosampaio12** [SERMIL/portal#287]
O valor da multa mínima foi atualizado para R$3,81  a partir de 01 abril 16 (trimestre), no sistema atualizado desde a data de 04/04/16, porém até o presente momento continua sendo emitido GRU no valor antigo R$ 3,71. È necessário rodar algum script no banco de dados para a atualização ter efeito?

**Comment by wagnerlopes** [comment]
Vou verificar.

**Comment by wagnerlopes** [comment]
@fabiosampaio12 

Verifiquei a questao da multa e a GRU é gerada com o valor que está na tabela que voce atualizou.
Eu reiniciei o servidor do alistamento, acho que o valor antigo estava em cache.
Também tem o caso de cidadao que se alistou antes da atualização da tabela e deve ter gerado a GRU antes, e ficou com o valor antigo.
Vamos ver se reiniciando o serviço a GRU sai correta. Tem como testar?
