### ISSUE TITLE
 Relatórios 8090 e 8092 do SERMIL

### ISSUE THREAD

**Issue by fabiosampaio12** [SERMIL/portal#297]
A 5ª RM através de DiEX solicitou  posição quanto aos relatórios citados ( Relatório 8090 Mapa de Apresentações no EXAR -Tempo na Reserva por OM) que não apresenta nenhum resultado, ou seja gera um pdf em branco relativo às OM da 5ª RM, comprometendo a avaliação da situação real, quanto à apresentação dos reservistas por ocasião do Exercício de Apresentação da Reserva.Quanto ao Relatório 8092 - Estatística de Acesso ao EXARNET a reclamação é que apresenta somente o universo de reservistas na condição de apresentados, não  separando por RM. Informam que existe a necessidade desse controle e solicitam  que seja verificado a possibilidade de ajuste no  sistema a fim de atender a essa demanda,apresentando os reservistas dentro de suas respectivas RM, com vistas a uma maior exatidão na apresentação dos dados

**Comment by wagnerlopes** [comment]
Preciso rever os SQL dos relatórios, mas no momento não é prioridade mexer nos relatórios do EXAR.
Só depois da seleção 2016.
