### ISSUE TITLE
Relatório 8079 (Militares sem Cargo na OM)  

### ISSUE THREAD

**Issue by fabiosampaio12** [SERMIL/portal#298]
O Chefe do Estado-Maior da 5ª Região Militar através de DIEx solicitou a possibilidade de alteração na apresentação do Relatório 8079 (Militares sem Cargo na OM)  alegando que atualmente apresenta de forma genérica a relação dos militares sem cargo nas OM, comprometendo a celeridade na realização
de auditoria, alegando que a alteração solicitada permitiria saber dentro do universo dos militares sem cargo na OM, o destino de mobilização (Ativa, Disponibilidade com Destino, Disponibilidade sem Destino, Além da Disponibilidade, Reservado, Especial, Outra Força ou Apenado), viabilizando dessa forma uma rápida e eficiente análise dos dados apresentados.

**Comment by wagnerlopes** [comment]
solucionado na versão 5.3.3
