### ISSUE TITLE
Erro ao cadastrar Certificado para cidadao

### ISSUE THREAD

**Issue by 6975usa** [SERMIL/portal#30]
Ao tentar cadastrar um certificado para um cidadao no portal, obtive a seguinte excecao:

Error setting expression 'rmLista' with value ['', ]

Erro inesperado durante a execução da solicitação.

Suporte Técnico: sermilweb@dgp.eb.mil.br

   Mensagem de erro:
   Could not commit JPA transaction; nested exception is javax.persistence.RollbackException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.6.0.v20150309-bf26070): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: java.sql.SQLIntegrityConstraintViolationException: ORA-01400: não é possível inserir NULL em ("SSM00"."OM"."CODIGO")

Error Code: 1400
Call: INSERT INTO OM (CODIGO, BAIRRO, CAIXA_POSTAL, CEP, DESCRICAO, ENDERECO, MOB_RESP, OM_TIPO, PRIORIDADE, QE_TIPO, SIGLA, MUNICIPIO_CODIGO, RM_CODIGO) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
	bind => [13 parameters bound]
Query: InsertObjectQuery(CODOM - SIGLA)

Provavelmente error de validacao de campos.

**Comment by 6975usa** [comment]
Como ja estou nesse codigo, posso conserta-lo.

**Comment by wagnerlopes** [comment]
Geralmente ocorre quando a lista nao foi preenchida, no caso rm aciona a lista de OM.
Em SERMILWEB estava ocorrendo isso porque como o servidor anda muito lento, as pessoas nao esperam as listas carregarem e seguem para a action sem os dados necessarios. Veja se é o caso de validar a entrada e voltar para input se for o caso.

**Comment by 6975usa** [comment]
Reslvido.
Fiz a validacao dos campos. Uma vez que tudo chega preenchido nao nenhuma excecao é lancada .
