### ISSUE TITLE
Certificado de Reservista

### ISSUE THREAD

**Issue by fabiosampaio12** [SERMIL/portal#300]
Ao tentar lançar o certificado de reservista 2ª categoria o sistema está apresentando a mensagem de erro anexa. 
![erro cadastrar cr 2 categoria](https://cloud.githubusercontent.com/assets/12251958/14783469/2f418d44-0ac6-11e6-94a2-08dcfdb2e187.jpg)

**Comment by wagnerlopes** [comment]
Este erro é o mesmos que descrivi no issue #301.
Ver o comentário lá.
@fabiosampaio12

**Comment by wagnerlopes** [comment]
Corrigido na versão 5.3.3

**Comment by wagnerlopes** [comment]
Solucionado na versão 5.3.3
