### ISSUE TITLE
Erro ao mudar OM na Aba -> Militar

### ISSUE THREAD

**Issue by sgtlima** [SERMIL/portal#301]
Ao mudar a OM de um militar, na aba Informações -> Militar apresenta o erro abaixo. 
RA que apresentaram o erro ao mudar da 16CSM para 28 GAC. 
**RA - 161732522370 - LUAN MOROSO COELHO
RA - 161732523691 - WAGNER TROMBIM**
![erro](https://cloud.githubusercontent.com/assets/14078817/14791234/619660ce-0aeb-11e6-8751-eb4152058600.png)

**Comment by wagnerlopes** [comment]
Analisei o erro e localizei a raiz do problema.
Descrição para registar futuros erros iguais:

A entidade Cidadao está associada com a Entidade Om através de um mapeamento na JPA ManyToOne da seguinte forma:

`@ManyToOne
 @JoinColumn(name = "OM_CODIGO", referencedColumnName = "CODIGO")`

Por sua vez a Entidade Om está associada com a Entidade OmCabecalho com uma mapeamento OneToOne da seguinte forma:

`  @OneToOne(mappedBy="om", fetch=FetchType.EAGER, cascade=CascadeType.ALL, orphanRemoval=true)`

Dessa forma ao salvar dados de OM automaticamente são salvos dados de OM_CABECALHO, o que está correto.

O que tem ocorrido é que **ao salvar dados de CIDADAO também está sendo salvo dados de OM**, o que **não está correto**, porque neste momento em CIDADAO só temos o CODOM da OM e as demais informações estão nulas, inclusive OM_CABECALHO, e o sistema ao tentar salvar OM_CABECALHO vazio, apresenta o erro reportado.

Pela documentação da JPA no mapeamento `@ManyToOne` quando não é informado o atributo cascade, **não deveria ser cascateado nenhuma ação para a entidade associada**, neste caso OM, mas está sendo cascateado a operação de persistência e levando junto em cascata a operação de persistência em OM_CABECALHO.

Minha solução foi adicionar no mapeamento em CIDADAO:

`@ManyToOne(cascade=CascadeType.REFRESH)`

Desta forma apenas a operação de refresh da entidade é cascateada para a entidade OM, ou seja somente um SELECT, desta forma UPDATE, INSERT e DELETE ficam de fora. Nos teste que fiz funcionou.

A dúvida que fica é: será um bug ou issue da nova versão da JPA 2.6.2? Não encontrei referência nos fóruns do assunto.

**Comment by wagnerlopes** [comment]
Corrigido na versão 5.3.3

**Comment by wagnerlopes** [comment]
Solucionado na versão 5.3.3
