### ISSUE TITLE
CAM de Junta criada recententemente saindo em BRANCO

### ISSUE THREAD

**Issue by sgtlima** [SERMIL/portal#303]
Foi informado e testado que a JSM recententemente criada de Olinda Nova do Maranhão, estão com seus alistados no sistema ao tentar emitir o CAM saindo em branco. 
Neste RA: 272060010019, pode ser verificado o caso citado. E um alistamento feito por esta junta.

**Comment by 6975usa** [comment]
Oi Lima
Vc pode me passar por favor ?
1) Nr da Junta
2) Nr da CSm
Grato

**Comment by 6975usa** [comment]
Oi @sgtlima 
Vc pode me passar por favor ?
1) Nr da Junta
2) Nr da CSm
Grato

**Comment by sgtlima** [comment]
@6975usa  Tentente 
CSM: 27
Junta: 206
