### ISSUE TITLE
Erro ao salvar alterações

### ISSUE THREAD

**Issue by fabiosampaio12** [SERMIL/portal#304]
O SERMIL está com erro ao salvar alterações na ficha do cidadão. Apresenta a mensagem "MENSAGEM NULA" e não salva a alteração. No caso enviado anexo estamos tentando alterar a situação militar de distribuído para Excesso de Contingente. Ao salvar está apresentando a mensagem anexa. 
![erro ao salvar](https://cloud.githubusercontent.com/assets/12251958/14851875/21d8ee92-0c59-11e6-879a-eb3c0e46dd1d.JPG)

**Comment by wagnerlopes** [comment]
Tentei acertar a questao de salvar certificado e aba militar, mas esta causando este outro erro.
Vou montar uma versao de emergencia e substituir essa do portal.

**Comment by wagnerlopes** [comment]
Solucionado na versão 5.3.3
