### ISSUE TITLE
Erro nao validar CPF no Alistamento On-line

### ISSUE THREAD

**Issue by sgtlima** [SERMIL/portal#305]
Foi informado através do cidadão ODAILSON DE LIMA BARBOSA, de CPF 078.863.375-90. 
Que seu CPF não esta sendo validado no site, apresentando a seguinte massagem na imagem abaixo. Foi feita a consulta o site da Receita Federal e o CPF encontrasse Ok. 
![sippes erro](https://cloud.githubusercontent.com/assets/14078817/14853933/fda53a16-0c63-11e6-8f46-0460f24528c5.jpg)

**Comment by wagnerlopes** [comment]
Parece que tem algum problema com o CPF, a consulta nao esta retornando resultado.
Outros cpf estao ok,  vou verificar se o cpf desse cidadao nao consta da base da receita ou tem algum problema que impede a consulta de prosseguir.

**Comment by wagnerlopes** [comment]
Serviço bloqueado no SIPPES por excesso de acessos.
Implementando Kaptcha na tela de pesquisa de CPF para evitar bots e outros programas de vasculhamento da Internet.
