### ISSUE TITLE
Erro ao Cadastra informações de JSM

### ISSUE THREAD

**Issue by sgtlima** [SERMIL/portal#306]
Ao cadastrar as informações de JSM aparece o erro informado abaixo, a informações da junta também seguem em imagem. 
![e2](https://cloud.githubusercontent.com/assets/14078817/14887586/daa6006c-0d2c-11e6-9ea1-985a4016cbe9.jpg)
![e1](https://cloud.githubusercontent.com/assets/14078817/14887587/daaa20fc-0d2c-11e6-880c-8ca7f5bf2ce6.jpg)

**Comment by wagnerlopes** [comment]
Solucionado na versão 5.3.3

**Comment by sgtlima** [comment]
Informo que foi recebido pelo suporte, também foi testado a tela. 
E o erro persiste, mesmo usando a versão 5.3.3 
![erro01](https://cloud.githubusercontent.com/assets/14078817/15115673/7f372500-15d6-11e6-8e81-ca95074fa946.jpg)
![erro2](https://cloud.githubusercontent.com/assets/14078817/15115688/8e27d94c-15d6-11e6-96e4-2fca7040a8e7.jpg)

**Comment by wagnerlopes** [comment]
Estou verificando e a tarde já vai estar sem erro.
Em 09/05/2016 11:10 AM, "Leonardo Lima de Oliveira" <
notifications@github.com> escreveu:

**Comment by wagnerlopes** [comment]
Corrigido.
