### ISSUE TITLE
Cadastramento de JSM tributária

### ISSUE THREAD

**Issue by fabiosampaio12** [SERMIL/portal#307]
Não está sendo possível cadastrar as JSM tributárias devido ao campo número de CS não estar disponível no cadastro da JSM. Houve alguma alteração no processo para cadastramento de JSM tributária, devido a ser criado o menu CS? Seg
![cadastramento de jsm tributaria](https://cloud.githubusercontent.com/assets/12251958/14887718/60984716-0d2d-11e6-8a67-5a9c64565d37.JPG)
ue abaixo a mensagem de erro.

**Comment by wagnerlopes** [comment]
Na mudança de modelo de dados para contemplar as novas funcionalidades de CS, danificou este módulo.
Corrigido na versão 5.3.3
