### ISSUE TITLE
Erro ao alterar siatuação militar

### ISSUE THREAD

**Issue by fabiosampaio12** [SERMIL/portal#308]
os delegados estão reclamando de um erro que o sistema está apresentando ao alterar a situação militar. Segue anexo uma tela com erro apresentado. 
![erro situacao militar](https://cloud.githubusercontent.com/assets/12251958/14896036/2a2dd810-0d52-11e6-907e-3a74f6672ee0.JPG)

**Comment by wagnerlopes** [comment]
Estou sabendo de todos esses erros.
Já quase terminei de fazer a versão 5.3.3 com a revisão do código pra evitar os diversos erros reportados nos ultimos dois dias.

**Comment by wagnerlopes** [comment]
Solucionado na versão 5.3.3
