### ISSUE TITLE
Inserir de fotografia de cidadão

### ISSUE THREAD

**Issue by fabiosampaio12** [SERMIL/portal#31]
Informo que ao tentar salvar a fotografia anexa no perfil do general Cmt Bda, apresenta uma tela de erro informando que a fotografia está fora do padrão, apesar da fotografia estar nos padrões exigidos pelo sistema. 
Seguem dados de teste: Nome: Jorge Cardoso Martins, RA 150992002041
![gen](https://cloud.githubusercontent.com/assets/12251958/7711249/ab05a404-fe3f-11e4-8c66-146228b739c1.png)
![general](https://cloud.githubusercontent.com/assets/12251958/7711250/ab089556-fe3f-11e4-98da-3f0425716bd9.jpeg)
![1](https://cloud.githubusercontent.com/assets/12251958/7711253/ac20844e-fe3f-11e4-804d-c721dc8027a3.png)

**Comment by wagnerlopes** [comment]
Carreguei a foto com sucesso no Portal. Não sabemos porque falhou com, talvez o servidor estivesse sobrecarregado. Quando ocorrer novamente vamos tentar descobrir o motivo.
