### ISSUE TITLE
Erro solicitação de alteração de tributação 

### ISSUE THREAD

**Issue by fabiosampaio12** [SERMIL/portal#310]
A 2ª RM relata que solicitou algumas alterações de tributação e o sistema trocou os números de CS e algumas ficaram até com um sinal de negativo na frente do número da CS. Solicito a gentileza de verificar o que está ocorrendo. Segue print da tela que está com números de CS errado. 
![alteracao de tributacao](https://cloud.githubusercontent.com/assets/12251958/14917358/07b6ebc0-0df5-11e6-980c-307093c1d674.JPG)

**Comment by wagnerlopes** [comment]
Limpei a tabela de Tributacão. Não era possivel aproveitar os dados após a modificação da modelagem do banco de dados visando atender os novos requisitos da CS para o ano atual.
Solicitar a 2, 3 e 4 Rm que insiram novamente as informações usando a interface 5.3.3
Se apresentar erro relatar para mim.
@fabiosampaio12
