### ISSUE TITLE
Atualização de JSM 

### ISSUE THREAD

**Issue by fabiosampaio12** [SERMIL/portal#311]
Ao atualizar a tributação e número de CS da JSM Rio de Janeiro Realengo está apresentando a mensagem de erro anexa.
![jsm](https://cloud.githubusercontent.com/assets/12251958/14955961/bfc4798e-1053-11e6-91fc-36d4ae282485.jpg)

**Comment by wagnerlopes** [comment]
Tem que selecionar a CS e o municipio, a caixa esta com selecione marcado.

**Comment by fabiosampaio12** [comment]
Foi selecionado. Apos o erro eu retornei e estava sem o município. Inclusive hoje a reclamação está geral inclusive no alistamento ONLINE que não carrega a tabela município no alistamento.

**Comment by wagnerlopes** [comment]
Sampaio,
Eu testei durante o final de semana e estava carregando todas as listas.
As vezes pode estar demorando um pouco porque o servidor pode estar
sobrecarregado.
Tem que ter um pouco de paciencia com as listas porque sao muitas,
ocupacao, municipio, jsm, pais, etc...
O pessoal quer tudo rapido mas sao muitos usuarios online ao mesmo tempo.
Vou olhar mas pede pro pessoal esperar a carga, nao adianta tentar salvar
sem carregar que da erro mesmo.

2016-05-02 10:56 GMT-03:00 Ten Sampaio <notifications@github.com>:

**Comment by wagnerlopes** [comment]
Hoje pela manha ja foram alistados online mais 304 cidadaos, todos com
dados corretos municipio etc.
Veja que o que pode estar acontecendo é letidao mesmo no carregamento das
listas.
Nesse caso vamos ter que melhorar a performance do servidor.
Daqui pra frente a tendencia é aumentar bastante a quantidade de acessos ao
site pra alistamento.



Em 2 de maio de 2016 11:01, Wagner Lopes <wagner.luis.alopes@gmail.com>
escreveu:

**Comment by wagnerlopes** [comment]
SAMPAIO, ESTA JSM 2/162 REALENGO É NOVA?

Em 2 de maio de 2016 11:11, Wagner Lopes <wagner.luis.alopes@gmail.com>
escreveu:

**Comment by fabiosampaio12** [comment]
A JSM é nova, foi criada para desafogar outra JSM tributária.

**Comment by wagnerlopes** [comment]
Ok, foi o teste que faltou fazer, JSM tributaria nova, estava faltando as
Info auxiliares, dava null e gerava erro.
São muitos dados pra validar. Faltou um teste, ferrou.
Como tive que mexer em muita coisa na modelagem do banco por causa da CS
permanente, alistamento online e do agendamento, vamos ter que validar
muitas partes do sistema novamente.
Por isso que não gosto de mexer tanto assim no Banco de dados e no sistema.
Mas este ano está tendo muita mudança nos processos, está afetando quase
tudo. Os erros vão ser uma constante até conseguirmos estabilizar isso de
novo.
Vai repassando os erros que vou acertando o mais rapido possivel.


2016-05-02 14:40 GMT-03:00 Ten Sampaio <notifications@github.com>:

**Comment by fabiosampaio12** [comment]
Tá certo coronel. Esse é o preço que temos que pagar devido as solicitações de alterações no sistema, com todas essas mudanças nos processos do serviço militar. Vou tentar acalmar os ânimos dos usuários.Desde já agradeço o pronto atendimento.

**Comment by wagnerlopes** [comment]
Sampaio,

Corrigi o problema da JSM e da situacao militar do cidadao.
Faça outros testes e veja se esta ok mesmo e se nao aparece erro novamente.


Em 2 de maio de 2016 15:02, Ten Sampaio <notifications@github.com> escreveu:

**Comment by wagnerlopes** [comment]
Corrigido.
