### ISSUE TITLE
Campo Local e Data de Emissão

### ISSUE THREAD

**Issue by fabiosampaio12** [SERMIL/portal#315]
Na emissão do CDI o campo Local e Data de emissão deverá ser aumentado pois não comporta tamanho de cidades  como Pindamonhangaba SP, 03/05/2016.

**Comment by wagnerlopes** [comment]
Esse erro o Borges verifica e acerta o relatorio de impressao.

Em 3 de maio de 2016 16:56, Ten Sampaio <notifications@github.com> escreveu:
