### ISSUE TITLE
Erro no número das CS

### ISSUE THREAD

**Issue by fabiosampaio12** [SERMIL/portal#316]
A 3ª RM levantou um problema informando que os números das comissões de seleção da RM citada, estão divergentes dos números corretos. Encaminho anexo  cópia do relatório (Rel 8014 - Relatório de Tributação de JSM em vigor) com números  de CS errados. Peço a gentileza de verificar. 
![erro numero cs](https://cloud.githubusercontent.com/assets/12251958/15023516/287e3636-1207-11e6-889c-800764f82622.JPG)

**Comment by wagnerlopes** [comment]
Estou alterando todos os relatorios que apresentam numero de CS, 8014,
8015, 8024 e 8035.

Como a modelagem do banco de dados foi alterada, para atender aos
requisitos do Agendamento de Seleção, endereço de CS, funcionamento, etc,
antigamente a tabela de JSm tinha direto o numero da CS que as RM informam.
Agora na tabela de JSM e Cidadao aparece o código interno de CS usado pelo
banco de dados e não mais o numero de CS das RM.
Eu já tinha alterado nas telas, acredito que em todos os pontos em que
aparece a CS, agora estou acertando os relatorios.
A noite coloco no ar as alterações.


Em 4 de maio de 2016 14:47, Ten Sampaio <notifications@github.com> escreveu:

**Comment by wagnerlopes** [comment]
Corrigido.
