### ISSUE TITLE
Alteração de OM do conscrito

### ISSUE THREAD

**Issue by fabiosampaio12** [SERMIL/portal#317]
A 2ª RM relatou e fiz os testes referentes a alteração de OM do conscrito. Ao tentar fazer alteração de OM apresenta uma mensagem de erro informando que a QM é obrigatória. No cidadão em questão coloquei a QM e salvou normalmente, porém, os conscritos não possuem QM, entretanto, não poderá ser um ítem obrigatório. Segue anexo a tela do teste. 
![exigir qm alteracao om](https://cloud.githubusercontent.com/assets/12251958/15025100/0de40100-120e-11e6-8dd0-bdd58c2d88b9.JPG)

**Comment by wagnerlopes** [comment]
Hum , passou batido, não era pra QM estar obrigatória, foi o copiar e
colar, acabou indo codigo html errado pro campo QM.


Em 4 de maio de 2016 15:37, Ten Sampaio <notifications@github.com> escreveu:

**Comment by wagnerlopes** [comment]
Campo QM opcional.
Corrigido.
