### ISSUE TITLE
Erro ao Gerar Relatório 8117  

### ISSUE THREAD

**Issue by sgtlima** [SERMIL/portal#318]
![erro rel 8117](https://cloud.githubusercontent.com/assets/14078817/15044151/5099de34-12a9-11e6-8ba9-fc0c6999b42b.jpg)
Ao selecionar a JSM, não abre a opção de selecionar CSM. Como mostra na imagem.

**Comment by wagnerlopes** [comment]
Estou conseguindo a lista.
Em 05/05/2016 10:11 AM, "Leonardo Lima de Oliveira" <
notifications@github.com> escreveu:

**Comment by wagnerlopes** [comment]
Corrigido.
