### ISSUE TITLE
Mensagem ao Cidadão - Salvador

### ISSUE THREAD

**Issue by fabiosampaio12** [SERMIL/portal#319]
O Maj Karpiuck  PRM Salvador está reclamando que o sistema está enviando mensagem ao cidadão com situação militar de Excesso de Contingente, informando que ele deve comparecer a JSM na data do carimbo do CAM para receber o Documento (CDI), porém, o cidadão não possui CAM e nem carimbo no documento. Peço a gentileza de verificar as mensagens que estão sendo encaminhadas para o cidadão que compareceu a CS Permanente. Talvez seja necessário revê-las. Não estou enviando anexo com a mensagem que o cidadão recebeu, pois está somente no Whatsapp do TC Mauro Tadeu.

**Comment by wagnerlopes** [comment]
Só quem recebe está mensagem é situação militar 8, excesso, está difícil de
entender o que ocorreu.
Em 05/05/2016 3:06 PM, "Ten Sampaio" <notifications@github.com> escreveu:

**Comment by wagnerlopes** [comment]
Resolvido.

**Comment by fabiosampaio12** [comment]
Informo que os chefes de PRM e cidadãos continuam reclamando das mensagens que estão sendo enviadas ao cidadão que fez o alistamento ONLINE, pois não possuem CAM e estão recebendo a mensagem anexa. 
![mensagem alistamento online](https://cloud.githubusercontent.com/assets/12251958/15359612/809bdf9c-1ce0-11e6-9809-15c49a6b712f.JPG)

**Comment by wagnerlopes** [comment]
Sampaio, está mensagem só aparece para as JSM que estão com a coluna
Internet = N no banco de dados.
Eu tinha acertado o banco, mas sempre alguém altera o status para N nas JSM
que estão fazendo alistamento online.
Pede pro Rômulo alterar o banco, colocando
Update jsm_info
Set internet = 'S'
Where csm_codigo = ?

Fazendo isso para todas csm que estão fazendo alistamento online a msg muda.
Em 18/05/2016 10:09 AM, "Ten Sampaio" <notifications@github.com> escreveu:

**Comment by fabiosampaio12** [comment]
Update efetuada na JSM em questão, situação corrigida. Agradeço a atenção @wagnerlopes
