### ISSUE TITLE
Cadastramento de Taxas e Multas 

### ISSUE THREAD

**Issue by fabiosampaio12** [SERMIL/portal#321]
Usuário reclama que ao tentar cadastrar a Taxas e Multas na ficha do cidadão RA 280882197583 - PEDRO SILVA DA LUZ FILHO, apresenta a mensagem de erro anexa. 
![erro taxas e multas](https://cloud.githubusercontent.com/assets/12251958/15053127/71c725ca-12d7-11e6-817e-341528a54a7f.JPG)

**Comment by wagnerlopes** [comment]
Esse erro já está com enchendo o saco, vira e mexe ele aparece de novo. Já
arrumei umas 5 vezes este problema.
Em 05/05/2016 3:38 PM, "Ten Sampaio" <notifications@github.com> escreveu:

**Comment by wagnerlopes** [comment]
Corrigido.
