### ISSUE TITLE
Dados complementares CS

### ISSUE THREAD

**Issue by fabiosampaio12** [SERMIL/portal#324]
A nova implementação no sistema no menu RM, para as mesmas lançarem os dados complementares de CS não está salvando os dados cadastrados. Após o cadastramento dos endereços de CS as RM estão tentando cadastrar os períodos de funcionamento e exclusão de datas de funcionamento e não estão conseguindo salvar, porém não apresenta nenhuma mensagem de erro. Apenas não salva dos dados cadastrados. Peço a gentileza de verificar, pois foi estipulado o prazo para cadastramento para não atrapalhar o calendário de obrigações. 
![dados complementares cs](https://cloud.githubusercontent.com/assets/12251958/15218169/08dfb316-1835-11e6-839e-85bd9aa1781d.JPG)

**Comment by wagnerlopes** [comment]
Estou verificando, este erro e aquele da conversão de data não implementada estão desafiando.
Parece que o banco de dados resolveu não cooperar.

- **Problema 1:** alistar no portal data nascimento não converte pro padrao do BD.
- **Problema 2:** funcionamento de cs e exclusão não gravam no banco.
