### ISSUE TITLE
Alistamento ONLINE - JSM Blumenau 

### ISSUE THREAD

**Issue by fabiosampaio12** [SERMIL/portal#327]
A Junta de Blumenau - SC não está conseguindo alistar ONLINE, mesmo estando INTERNET "S" na tabela JSM_info. Qual seria uma possível solução?

CSM 16 
JSM 044

Aparece a mensagem abaixo, quando cidadão tentar fazer o alistamento. 

Atenção!
A Junta de Serviço Militar selecionada ainda não disponibiliza o Alistamento ONLINE.

Dirija-se à Junta de Serviço Militar mais próxima de sua residência e efetue seu alistamento. Para localizar um local de alistamento clique "aqui".

**Comment by wagnerlopes** [comment]
Vou ter que olhar o cadastro da Jsm, alguma informação está inconsistente.
Eu percebi que tem juntas com informações incorretas no cadastro. As RM
deveriam auditar as info de JSM através dos relatórios, fica difícil para
nós vermos mais de 5000 juntas.
Em 18/05/2016 1:31 PM, "Ten Sampaio" <notifications@github.com> escreveu:

**Comment by wagnerlopes** [comment]
@fabiosampaio12 @romulodba @aryene @andremb2211

Outra coisa,

Quando as informações são alteradas direto no banco de dados, por exemplo, foi feito update em internet = 'S' na tabela de jsm_info, o dado não altera automaticamente na aplicação que está online.
Isto ocorre porque aplicação mantem um cache de dados internamente para otimizar as consultas, geralmente isso não é um problema se todos os dados são atualizados via aplicação.
No caso foi feita uma atualização "por baixo do pano" o que faz com que os dados fiquem inconsistentes durante um determinado período.
A solução é aguardar o cache sincronizar, ou dar um "REBOOT" na aplicação após o update. 
Foi o que acabei de fazer. Já está alistando novamente.
Todo problema começou com as alterações indevidas nas info de JSM.
 Fiquem atentos.
