### ISSUE TITLE
Erro ao gerar CDI

### ISSUE THREAD

**Issue by sgtlima** [SERMIL/portal#328]
Ao tentar gerar CDI pelo sermilweb, no RA:160689830960 aparece um erro. 
O seguinte erro abaixo. 
![erro ra](https://cloud.githubusercontent.com/assets/14078817/15369636/e1ea9f58-1d09-11e6-9448-11b7304801d2.png)

**Comment by sgtlima** [comment]
Informo também relacionado ao CDI, que foi gerado um CDI com a situação: Dispensado de Incorporação. O qual deveria Dispensado de seleção ou Excesso de contingente. 
![espelho cdi - sermil](https://cloud.githubusercontent.com/assets/14078817/15392765/ac37f324-1d9f-11e6-9fb5-ea927af9b274.png)

**Comment by wagnerlopes** [comment]
São sinônimos no processo do SERMIL.
Até hoje estes termos tem sido usados como sendo iguais.
O pessoal da SSMI deveria fazer uma busca na Lei e Regulamento e ver se
existe diferença. Para nós desenvolvedores tem sido tratado como a mesma
coisa.
Em 19/05/2016 8:57 AM, "Leonardo Lima de Oliveira" <notifications@github.com>
escreveu:

**Comment by 6975usa** [comment]
O RA informado (160689830960) realmente nao e´um RA valido. De alguma forma ele ja  estava na base de dados. 
O codigo do Sermil esta´ correto. 
Na minha opiniao esse issue pode ser fechado sem nenhuma alteracao no codigo.

**Comment by 6975usa** [comment]
O RA informado (160689830960) realmente nao e´um RA valido.
Foi feito um novo alistamento para o cidadao.
Consequentemente ele recebeu um novo RA 
O CDI foi impresso normalmente com esse novo alistamento.
Nao ha necessidade de mudar codigo
