### ISSUE TITLE
Certificados

### ISSUE THREAD

**Issue by wagnerlopes** [SERMIL/portal#33]
Surgiu em discussão na CSM a necessidade de controlar a emissão dos Certificados, principalmente a questão de que os cidadãos muitas vezes *não retiram o CDI na JSM*, e o mesmo acaba sendo destruído.
Para contemplar esta necessidade, proponho que seja criadas duas colunas na tabela **CID_CERTIFICADO**:

- Entregue (ou retirado) = S/N
- Anulado = S/N

* Assim quando o CDI for emitido a coluna entregue fica (N), quando o cidadão retirar passa para (S);
* Se o certificado for destruído Anulado passa de (N) para (S);
* Vamos poder manter o histórico dos certificados na tabela, sendo que apenas o que estiver válido, ficará com o status Anulado = N;

**Comment by 6975usa** [comment]
O sr acha que para a implementacao desssa funcionalidade sera necessario enviar Diex para todas as Juntas informando a nova sistematica?

**Comment by wagnerlopes** [comment]
Acho que agora não, depois, quando for normatizado, seria o caso.

**Comment by wagnerlopes** [comment]
Implementado no modelo (classe CidCertificado).
Falta alterar as telas do Portal.
