### ISSUE TITLE
QCP

### ISSUE THREAD

**Issue by fabiosampaio12** [SERMIL/portal#336]
Muitas OM's estão reclamando que os QCP estão desatualizados e também não estão conseguindo fazer as atualizações e quando tentam colocar o militar dentro de um cargo, na tela Militar do cidadão não aparece as frações (tela anexo)
![qcp](https://cloud.githubusercontent.com/assets/12251958/15674158/a18da826-2711-11e6-9cff-498f4c40fd48.JPG)

**Comment by wagnerlopes** [comment]
QCP está desatualizado mesmo, e depende da integração com DGP que o Rômulo
nao teve mais tempo de tocar. O que tem é isso que está disponível.
Quanto aparecer a lista, ela demora um pouco para aparecer, pode ser isso
que os usuários não estão conseguindo esperar, pois depende da velocidade
da internet local.
Em 31/05/2016 9:25 AM, "Ten Sampaio" <notifications@github.com> escreveu:

**Comment by wagnerlopes** [comment]
Estou pensando que a melhor solução é desativar essa funcionalidade do SERMIL.
Não vamos mais ter condição de manter a tabela de QCP atualizada, e fica essa funcionalidade perdida, com usuarios reclamando.
É algo que não agrega muito ao SERMIL.
Façam a votação a respeito. 
Eu voto por excluir o QCP do SERMIL, porque não é nossa responsabilidade manter esse dado. Isso é coisa do DGP, DCEM, EME.

@fabiosampaio12 @romulodba @6975usa

**Comment by 6975usa** [comment]
Cel @wagnerlopes  concordo com o sr.
Isso deve ser retirado do Sermil. Mesmo pq isso não é Sermil.
Vou levar esse assunto ao Cap Romulo e ao TC Bartz para ver os impacto disso na mobilizacao, e tb para definir a abrangencia do que pode ser retirado.
Vou porpor que todo o menu "Vida Militar" seja retirado.

@wagnerlopes @romulodba @fabiosampaio12

**Comment by wagnerlopes** [comment]
Só tem que tomar cuidado que a Mobilização depende de muitos campos da vida militar para controlar os reservistas, se a informação não estiver guardada não tem como dizer quem é quem na fase de mobilização de pessoal.
Tem que ser feito um estudo cuidados dos dados.

**Comment by 6975usa** [comment]
Converseio com o TC Bartz sobre esse assunto.
Ele ficou de me falar como essa decisão afetaria a mobilizacao.
