### ISSUE TITLE
CS Sermil

### ISSUE THREAD

**Issue by fabiosampaio12** [SERMIL/portal#337]
Por solicitação do Gen Pedrosa as CS - Comissões de Seleção,  da 5ª, 6ª,8ª e 9ª RM deverão funcionar em período integral, exceto, na sexta feira que  deverá funcionar apenas no período da manhã. Quando sistema fizer a distribuição escalonada dos conscritos para seleção, como ficará a sexta-feira, será encaminhado apenas metade do quantitativo de atendimentos diários?
Outrossim, existe algumas particularidades de CS volantes que também não possuem médico para os dois turnos. Haveria a possibilidade de escolher os turnos que a CS vai funcionar?

**Comment by wagnerlopes** [comment]
O agenda mento funciona baseado nas informações que a RM vai informar na tela de Funcionamento da CS, onde coloca a data inicial e final. O horário de agendamento são somente dois: 7h e 13h.

Sexta-feira eu já considero sempre na rotina apenas o agendamento das 7h da manhã em todas as CS.

Os feriados e dias sem expediente a RM informa na mesma tela as datas excluídas, se não informar ou se esquecer de colocar a data, vai ter gente agendada no dia esquecido.

Quanto as CS volantes não foi colocado em nenhum momento que havia o requisito de fazer agendamento em apenas um determinado período, tanto que nem existe parâmetro a respeito no sistema.

@romulodba está vendo o requisito surgindo do nada? É assim que começa a confusão.
