### ISSUE TITLE
Editar Cadastro de CS - Salvar - Erro

### ISSUE THREAD

**Issue by 6975usa** [SERMIL/portal#339]
Erro após tentar salvar cadastro da CS abaixo:
![sermil-erro2](https://cloud.githubusercontent.com/assets/6667748/15720196/b0fc4ddc-2809-11e6-9279-0efb4e95da80.png)
![sermil-erro3](https://cloud.githubusercontent.com/assets/6667748/15720207/bd473e44-2809-11e6-97a4-613d85a2a58d.png)
![sermil-erro](https://cloud.githubusercontent.com/assets/6667748/15720214/c8468d22-2809-11e6-80e5-874f6b22219f.png)

**Comment by wagnerlopes** [comment]
Veja a mensagem Falhou! Na tabela , isso significa que houve falha no
código javascript durante a inicialização por algum motivo.
Em 01/06/2016 3:02 PM, "Anselmo S Ribeiro" <notifications@github.com>
escreveu:

**Comment by wagnerlopes** [comment]
Como já estava em erro não tinha como continuar, ele tentou cadastrar algo
quando a página já tinha falha.
Em 01/06/2016 3:51 PM, "Wagner Lopes" <wagner.luis.alopes@gmail.com>
escreveu:

Veja a mensagem Falhou! Na tabela , isso significa que houve falha no
código javascript durante a inicialização por algum motivo.
Em 01/06/2016 3:02 PM, "Anselmo S Ribeiro" <notifications@github.com>
escreveu:

**Comment by wagnerlopes** [comment]
Fazendo uma pesquisa no banco de dados, descobri que a constraint foreign key na tabela CS_EXCLUSAO_DATA, estava com algum erro interno.
Ao tentar inserir o registro manualmente na tabela, ela sempre informava que a chave estrangeira não existia, mesmo quando o código da CS existia na tabela CS.
Apaguei a constraint Primary Key e Foregn Key da tabela, e recriei novamente ligando CS com CS_EXCLUSAO_DATA.
Fiz o mesmo teste e o insert funcionou.
Aparentemente havia algum erro na estrutura da tabela no banco de dados, essa tabela tinha sido criada com o nome CS_FERIADO e durante a remodelagem foi renomeada como CS_EXCLUSAO_DATA, pode ser que isso tenha feito que perdesse alguma referencia interna do Oracle que estava causando o erro.
Vamos continuar a monitorar para ver se o erro aparece novamente no sistema.
@romulodba @6975usa

**Comment by 6975usa** [comment]
O usuario ligou dizendo que conseguiu realizar a operacao
