### ISSUE TITLE
Painel -> Arquivos do sistema. Muito lento quando arquivo muito grande

### ISSUE THREAD

**Issue by 6975usa** [SERMIL/portal#34]
Ao clicar em "Painel -> Arquivos do sistema" o sistema demora muito a responder quando o arquivo é muito grande. Isso onera muito o servidor tornando-o lento.

Solucoes possiveis:
1) Limitar o numero de linhas retornadas no arquivo, ou
2) Criar item de menu para "Limpar arquivo de Log" sem presicar abri-lo.

**Comment by wagnerlopes** [comment]
O servidor está lento em quase tudo, acho que o melhor seria que o novo entrasse logo em funcionamento.
