### ISSUE TITLE
Layout de boleto CEF

### ISSUE THREAD

**Issue by 6975usa** [SERMIL/portal#349]
O TC Mauro Tadeu solicitou a mudanca do layout do boleto da CEF para se adequar ao modelo que ele recebeu da Febraban 
![febraban01](https://cloud.githubusercontent.com/assets/6667748/16080205/045ac8ee-32de-11e6-8bcc-04e827f98444.png)

**Comment by 6975usa** [comment]
@aryene vou pedir a vc para providenciar essa mudanca.
Caso haja alguma duvida favor esclarecer com o TC Mauro Tadeu.

**Comment by wagnerlopes** [comment]
Vou dar início a construção do módulo de Taxas e Multas.
Preciso saber se esse layout proposto irá mesmo ser implementado.
Por enquanto vou manter o layout de boleto tradicional, a equipe de homologação da CEF não questionou até agora o formato do layout do nosso boleto.
Solicito esclarecimentos @6975usa @Maurotadeu @raseng

**Comment by wagnerlopes** [comment]
* Código de barras do Boleto CEF alterado;
* Aguardando retorno da validação do Boleto CEF pela equipe de homologação da CEF.

**Comment by wagnerlopes** [comment]
Concluído na versão 5.4.7
