### ISSUE TITLE
Proposta de consolidacao de nomes dos sistemas

### ISSUE THREAD

**Issue by 6975usa** [SERMIL/portal#35]
A fim de causar uma identidade no usuario, proponho que, a exemplo do exarnet, o sermilweb e o sermil tenham url e banner com seus reais nomes

1) SERMILWEB 
A url ja esta correta: http://www.sermilweb.eb.mil.br/
Mas o banner precisa mudar para constar o nome Sermilweb ao inves de sermil como vemos abaixo:
![1](https://cloud.githubusercontent.com/assets/6667748/7755266/3932ca42-ffc9-11e4-83e2-7637a8b6c791.png)

2) SERMIL
A url deveria ser  http://www.sermil.eb.mil.br/
E o banner deveria constar o nome Sermil ao inves de Sermilweb conform abaixo:
![2](https://cloud.githubusercontent.com/assets/6667748/7755337/b53b36d8-ffc9-11e4-8739-e028fd346b95.png)

Gostaria da opinião da equipe quanto a isso. Principalmente no que se refere a impedimentos tecnicos e administrativos a essa mudanca.

**Comment by wagnerlopes** [comment]
Sempre achei melhor que fosse só SERMIL, mas hoje é mais fácil padronizar para SERMILWEB porque para alterar a URL temos que solicitar ao CITEx é isso sempre é complicado.
O Alexandre tem que criar novo banner e ícones para deixar tudo igual.

**Comment by wagnerlopes** [comment]
Nome padão: SERMILWEB.
