### ISSUE TITLE
Módulo Taxas & Multas

### ISSUE THREAD

**Issue by 6975usa** [SERMIL/portal#350]
O TC M. Tadeu solicitou que fosse criado um modulo para leitura do arquivo que recebe com a comprovacao do pagamento de taxas e multas.

Teor do arquivo recebido.

A2                    SERVIÇO MILITAR MULT   ECT - CORREIOS      2016060100000103                                                                  ECT
G36021000000001705008201606012016071486690000000030600894356200000000009622238912000000000306000028600000001000000201  
G36021000000001705008201606012016071486640000000030100894356200000000009622238912000000000301000028600000002000000201  
G36021000000001705008201606012016071486620000000031100894356200000000009622238912000000000311000028600000003000000201  
G36021000000001705008201606012016071486650000000032600894356200000000009622238912000000000326000028600000004000000201  
Z00000600000000000001244                                                                                                                           ECT

**Comment by wagnerlopes** [comment]
A codificação dos campos consta da documentação? Não lembro de ter recebido.
Temos somente a codificação de campos de código de barras da FEBRABAN.
Em 15/06/2016 9:50 AM, "Anselmo S Ribeiro" <notifications@github.com>
escreveu:

**Comment by 6975usa** [comment]
Sim
Tenho toda a documentacao. Esta tudo bem coerente. Acho q nao vai haver problemas pra criar esse modulo.

**Comment by wagnerlopes** [comment]
Vai dar trabalho porque além de decodificar os campos precisa ser criado
toda uma modelagem no banco para registrar geração de boleto, pagamento,
etc, até o registro em cid_arrecadacao. Não é tão simples, pra sair algo
funcional vai demandar bastante trabalho.
Em 15/06/2016 9:57 AM, "Anselmo S Ribeiro" <notifications@github.com>
escreveu:

**Comment by wagnerlopes** [comment]
Vamos considerar esta funcionalidade um novo módulo completo, com esforço
alto de desenvolvimento, nada de subestimar a tarefa que depois sobra pra
equipe toda a carga de trabalho.
Tem que ser criado todo o processo automatizado de registro de
taxas/multas, que hoje é quase todo manual, em diversos orgãos, com
registro no sistema apenas no final.
Em 15/06/2016 10:00 AM, "Wagner Lopes" <wagner.luis.alopes@gmail.com>
escreveu:

**Comment by 6975usa** [comment]
O sr tem razao.
O esforco 'e grande. Tem q registrar desde a geracao do boleto at'e seu pagamento.

**Comment by 6975usa** [comment]
Cel @wagnerlopes 
O Maj Sanchez tem me cobrado o inicio dos trabalhos nesse modulo.
Tenho falado pra ele que nao foi iniciado pois todos os esforcos estavam na Pre-Dispensa.
Ontem, no entanto ele falou que a Pre-Dispensa ja acabou e pediu uma posicao a respeito.
O que respondo ao Maj Sanchez?

**Comment by wagnerlopes** [comment]
Anselmo, (@6975usa): 
Começa a fazer analise, mas precisa verificar tudo, desde o inicio, requisitos junto aos usuarios, jsm, csm, delegacia, RM, DSM, Bancos.
Depois que levar as necessidades e tiver o processo modelado no papel, qual é o fluxo dos dados, como vai ser lançado, como vai ser o retorno da informacao, pode-se comecar a fazer a modelagem das informacoes a serem mantidas no Banco de Dados.
Depois podesse comecar a pensar na programacao em Java.
Se comecar a fazer programacao em Java logo de cara, ja vamos ter problema de novo. Vai ficar tudo meia boca e bagunçado. Eu conversei sobre isso com o Romulo, ele disse que ia gerenciar todo esse processo.
Não podemos ficar fazendo tudo de qualquer jeito no sistema, já foi feito muito assim, e sempre vira uma dor de cabeça, especialmente para mim, no final das contas.
Gostaria que desta vez pelo menos a coisa fosse feita mais devagar, mas que tivesse menos problemas, essa funcionalidade ficou sendo cogitada a pelo menos 10 anos, então não vamos ficar correndo, porque quem era responsavel ficou uma decada enrolando para contactar as Instituicoes Bancarias para dar um retorno.
Não fique implementando coisas direto no sistema, e fazendo push no GitHub, mantenha os branchs dessas tentativas na base local. Quanto menos poluicao na nuvem melhor.

**Comment by wagnerlopes** [comment]
Outra coisa, a modelagem do processo deveria ser feita por alguem que esta solicitando, pode ser o Sanchez, alguem da SSMI, alguem que nao seja nós do desenvolvimento.
O processo é como eles imaginando o funcionamento de todo esse processo de gerar boleto, cidadao pagar, JSM registrar, banco retornar, etc.
Isso qualquer um com um pouco de boa vontade pode fazer.

**Comment by 6975usa** [comment]
Sim sr
Vou providenciar o inicio dessa documentacao e mantenho o sr informado.

**Comment by wagnerlopes** [comment]
Não aceite do pessoal aquela conversa de que é só fazer uma coisinha ou
outra.
Temos que fazer um módulo completo de Pagamento e Recebimento de
Taxas/Multas.
Vai exigir um bom trabalho. Fica você com o encargo desse módulo que será
pessado. Veja com os bancos (são tres intituicoes) como será o recebimento
da informação, tem que
ser o mais integrado possivel com o SERMIL, o ideal seria um Web Service
para irmos buscar o resultado e dar baixa, se nao der, um arquivo de carga
periodico, algo assim.
Eu vou tentar avançar com o módulo de Seleção Online, que ficou parado
desde que comecei com o agendamento, e continuar a manter em dia as
informacoes de CS, Selecao e Agendamento.
Aqueles pedidos do Sampaio com choradeira de Delegado, JSM e etc, é
besteira, eles ficam inventando moda, deixa ele registrar os Issue, se
for o caso eu acerto. A maioria é falta de experiencia do pessoal com o Sv
Mil.



2016-07-21 12:39 GMT-03:00 Anselmo S Ribeiro <notifications@github.com>:

**Comment by 6975usa** [comment]
Sim sr, vou fazer um trabalho completo quanto ao modulo de Taxas/Multas.
Conversei com o Maj Sanches ontem e ele me mostrou o fluxograma do processo que depois vou passar para o sr. Realmente esse processo envolve varias pessoas e varios lugares.

Quanto a CS gostaria de fazer uma sugestao: 1) Há informaçoes repetidas dentro do proprio Sermil. Por exemplo: o campo "Deseja Servir" está em tres lugares diferentes, alistamento, entrevista e Agenda. Ha outros campos que tb se repetem. 2) Os campos da tabela entrevista tem nomes horriveis. Eles se referem aos itens de uma documentacao recebida do CEP no Rio. Esse documento deve estar no email do sr.

**Comment by wagnerlopes** [comment]
@6975usa 
Eu sei, vou alterar a modelagem do banco de dados quanto aos dados de selecao.
Criei a tabela CS_SELECAO exatamente para poder extrair as informacoes da tabela CIDADAO, e deixa-la um pouco mais leve.
O problema é que mexendo na estrutura da tabela CIDADAO envolve uma grande alteracao nao só nas procedures do banco de dados, principalmente da distribuicao, como na aplicacao, no moelo, e relatorios.
Por isso tenho adiado o momento de fazer alteracoes mais profundas.
Sabe que vivemos em constante fogo cruzado de solicitacoes sem fim dos usuarios.

**Comment by wagnerlopes** [comment]
* Arquivo de retorno da CEF (Febraban 150 colunas) está disponível;
* Aguardando para iniciar desenvolvimento do módulo de leitura.

**Comment by wagnerlopes** [comment]
Foi concluída a implementação da leitura do arquivo padrão FEBRABAN 150 colunas, disponível a partir da versão 5.4.7 da aplicação
Caminho: Menu > Arquivos > Arquivo de Retorno Bancário.
