### ISSUE TITLE
Gerar GRU

### ISSUE THREAD

**Issue by fabiosampaio12** [SERMIL/portal#351]
Usuários do sistema estão reclamando que ao tentar gerar GRU o sistema está apresentando erro, ou seja,  o PDF não é gerado. Fizemos os testes e o erro está acontecendo. Peço a gentileza de verificar o problema.

**Comment by wagnerlopes** [comment]
Este é um dos relatórios que podiam apresentar erro na migração pro
Jasperreport 6.2.2, é orientado objeto, ou seja, não tem consulta SQL,
objeto é passado completo ao relatório.
Ao migrar testei na minha maquina e funcionou.
Precisa verificar que tipo de erro está ocorrendo.
Em 15/06/2016 10:16 AM, "Ten Sampaio" <notifications@github.com> escreveu:

**Comment by fabiosampaio12** [comment]
Fiz outros testes novamente e percebí que o erro está acontecendo quando o CPF é inválido. Possivelmente o sistema está fazendo a validação de CPF.

**Comment by wagnerlopes** [comment]
Mas vai gerar GRU pra CPF inválido ? Que tipo de usuário faz isso?
Em 15/06/2016 10:25 AM, "Ten Sampaio" <notifications@github.com> escreveu:
