### ISSUE TITLE
Erro ao consultar alistamento on-line

### ISSUE THREAD

**Issue by sgtlima** [SERMIL/portal#353]
O cidadão de ra: 170019233775 ao pesquisa no site alistamento.eb.mil.br retora no seguinte erro:
![erro01](https://cloud.githubusercontent.com/assets/14078817/16152794/cdd92a66-3479-11e6-977d-efb9102a9d06.jpg)

**Comment by 6975usa** [comment]
Resolvido
Alteracoes estão na Organização Sermil

**Comment by wagnerlopes** [comment]
Este erro ocorreu porque fica gente mexendo no sistema de forma errada, alteraram o cadastro do cidadão colocando situação militar = 2 (seleção), mandando pra seleção de forma indevida cidadão de municipio não tributário que não tem CS no cadastro.
Quem faz o encaminhamento para seleção é o programa de Seleção, mas tem usuário, *ROLHA* que teima em mandar cidadão pra CS dessa forma.
Depois quando roda o programa, ele desfaz tudo que este bando fez errado, e acaba com a bagunça.
