### ISSUE TITLE
JSM Tributárias - CS

### ISSUE THREAD

**Issue by fabiosampaio12** [SERMIL/portal#358]
As JSM tributárias  abaixo discriminados não estão aparecendo  para lançamento dos quantitativos de fichas de seleção, para que os cidadão sejam encaminhados para CS,  e o Cap Dos Santos -Adj SMR/2 solicitou que sejam adicionadas para lançamento da pré-dispensa, pois ja consta no PGC. 

2ª RM - 5ª CSM - 15ª Del Sv Mil - CS 013 - JSM 064 - JOSÉ BONIFÁCIO
2ª RM - 6ª CSM - 22ª Del Sv Mil - CS 013 - JSM 017 - AVANHANDAVA

**Comment by wagnerlopes** [comment]
Já foi resolvido.
Sincronizei as tabela JSM e SEL_JSM com as juntas tributárias do ano atual.
Se estiver faltando alguma JSM outra RM, precisa verificar se a tributação da junta está correta.
Não pode haver erro até o início da pré-dispensa.

**Comment by fabiosampaio12** [comment]
Informado ao  usuário. Qualquer Erro entro em contato para informar. Agradeço a atenção.
