### ISSUE TITLE
Validar CPF no usuário sermil

### ISSUE THREAD

**Issue by lucianaaquino** [SERMIL/portal#368]
Boa tarde gostaria de solicitar a validação do CPF do usuário do Sermil. Acontece que quando cadastrado o usuário no sermil foi percebido que o campo CPF não esta validando, pois podemos preencher com apenas 3 dígitos, letras ou número da identidade que o sistema aceita, desde já agradeço. Segue anexo de um dos casos de não validação do CPF.
[Ticket #876702.pdf](https://github.com/SERMIL/portal/files/359896/Ticket.876702.pdf)

**Comment by 6975usa** [comment]
Oi @lucianaaquino 
Obrigado por avisar isso. 
Importantíssimo mudarmos isso pois pode nos causar muita dor de cabeca um usuario com cpf errado.
Vou providenciar a mudanca para sair na versao 5.4.5

**Comment by 6975usa** [comment]
Solucao implementada e propsta no PR #372
