### ISSUE TITLE
Solicitações do PRM  - Salvador

### ISSUE THREAD

**Issue by fabiosampaio12** [SERMIL/portal#369]
Abro esse chamado para lembrar da necessidade da criação de um tipo de situação militar e de motivos de dispensa:

Envio abaixo solicitações do Cap Aguiar- PRM Salvador, para verificar se é pertinente as solicitações.

1) Situação Militar
Falta o evento "Excesso de Contigente (CS)" para atender aqueles que são dispensados na CS como B/2 e B/1 pela segunda vez, nso termos dao artigo 56 do RLSM.

2) Motivo da dispensa
Falta nos motivos a divisão dos "inaptos" para distinguir os tres tipos: de Inapto:
- Inapto (B/1) - de acordo coma legislação, deve retornar para a CS e na segunda vez deverá receber o CDI;  
- Inapto (B/2) - de acordo coma legislação, deverá receber o CDI (não recebe; pois Sermil não imprimi CDI para incapaz)
- Inapto (C) - de acordo com a legislação, deverá receber o CI (não recebe; pois Sermil não imprimi CI para incapaz)

Obs.: Não existe a revisão de uma motivo para os isentos  (INAPTO C) e só existe os "Notoriamente Incapaz". Mas nem todo "Inapto C" (obtido na comissão de Seleção) é um "Notoriamente Incapaz" (obtido mediante processo de isenção). 

Obs.: O Delegado pode mudar o status para permitir a impressão de documentos, mas em cidades como Salvador (e outras grandes) são em torno de 8000 incapazes o que é complicado para o Del SM trocar todos. Seria interessante a liberação na CS ou a divisão nos três tipos para que o B/2 e C possam ser liberados ainda na CS

3) Falta também para os que serviram e foram licenciados normalmente (por conclusão do Sv mIl) o motivo da dispensa "Reservista" que atenderia aos licenciado/desligado que não tenham sido "a bem da disciplina".

**Comment by wagnerlopes** [comment]
Não se cria situacao militar para cada questão particular encontrada, desse
jeito vamos ficar com centenas de situacoes militares.
Esse pessoal só inventa moda que não funciona. As situacoes sao as que
existem e sao suficientes para tudo. Excesso é Excesso e ponto final, não
existem subcategorias como ficam querendo criar.
A mesma coia vale para Inaptos.
Se ele quer ficar fazendo subdivisoes, pode usar o campo Anotacoes e
escrever um Livro sobre o cidadao em questao naquele campo, problema dele.

Sempre que alguem vier com essas ideias de malucas, pode dizer que os
valores dos campos foram analisados a fundo durante mais de 20 anos e
chegou-se a conclusao que sao suficientes, e nao serao mudados para o gosto
de cada delegado que passar pela funcao. Esse pessoal é muito burro. Arrego.
OK?

Em 18 de julho de 2016 10:19, Ten Sampaio <notifications@github.com>
escreveu:

**Comment by 6975usa** [comment]
Solucao Proposta implementada no  PR #372

**Comment by wagnerlopes** [comment]
Não existem 3 tipos de inaptos, isso é bobagem.

Em 19/07/2016 1:20 PM, "Anselmo S Ribeiro" <notifications@github.com>
escreveu:

**Comment by wagnerlopes** [comment]
Estão confundindo as coisas e trocando as bolas. Depois implementam coisa
errada e ficam consertando besteiras criadas por quem não entende do
assunto.

Em 19/07/2016 1:41 PM, "Wagner Lopes" <wagner.luis.alopes@gmail.com>
escreveu:
