### ISSUE TITLE
Entrevista da CS

### ISSUE THREAD

**Issue by wagnerlopes** [SERMIL/portal#37]
# Alterações solicitadas pelo CEP:

1. Dados da Ficha de Seleção

- Manter até Zona Residencial
- Os campos abaixo da zona mover para vida pessoal e transformar em campos de edição para serem alterados (carregar com os valores que estiverem no banco), é do endereço para baixo.

2. Vida Pessoal

- Passa a ser o segundo item na coluna da esquerda;
- Colocar os campos que citei no nr 1;
- Item Com quem mora?
 Quem trabalha na familia? (colocar check box com multiseleção)
 Quem sustenta?(multiseleção  tambem);

3. Arrimo de Família

- Passa a ser o item 3 no menu;
- Se for escolhido 'sim' parar a entrevista e navegar para próxima tela;

4. Escolaridade

-Colocar a lista de escolaridade do sistema;

5. Pré-qualificação

- Colocar a lista de padrões funcionais pré-qualificação;
- Se ficar em duvida eu te mostro como fazer para extrair da tabela de padrões;

6. Lazer

-Colocar a caixa de edição que permite redimensionar o tamanho.

7. Saude

- acertar maiuscula (Algum, Psiquiatrico, Fuma? Há 'Q'uanto, Alcool falta o)

Item: Possui parente usuario de drogas ou alcool? (mudar o texto)

Qual a gravidade? (tirar)
Isso afeta sua vida diretamente? (colocar) sim nao
Como? (caixa de edição)

- Tratamento psiquiatrico, colocar os mesmo itens ciam;

8. Ato Infracional

Qual? (colocar itens em linha separadas e permitir multipla escolha)

9. Deseja Servir

- Não, bloqueia itens seguintes
-Colocar Indicação de CS Especial

10. Expressão Oral

- acertar maiuscula/minuscula

11. Indicadores (Tela seguinte)

Texto:O conscrito será consideradoInapto K (tirar problema social)

Se escolher sim em algum campo,ir para avaliaçãi final e considerar INAPTO

**Comment by 6975usa** [comment]
Providenciando....
Caso tenha alguma duvida, pergunto.
