### ISSUE TITLE
Alteração do contato suporte no Alistamento Onl

### ISSUE THREAD

**Issue by andremb2211** [SERMIL/portal#370]
![image](https://cloud.githubusercontent.com/assets/12534223/16923013/7d9573a6-4cee-11e6-8873-e4a3997f8ce6.png)

**Comment by andremb2211** [comment]
@wagnerlopes fiz o commit com a alteração.

Alterado ´para conforme abaixo.

![image](https://cloud.githubusercontent.com/assets/12534223/16926851/0677a376-4d01-11e6-8194-c8afadda4599.png)

**Comment by 6975usa** [comment]
Resolvido no PR #374 
Esse issue pode ser fechado.
