### ISSUE TITLE
Erro - Acesso negado 

### ISSUE THREAD

**Issue by aryene** [SERMIL/portal#371]
No perfil DSM da um erro quando acessar RM -> Status dos processos.
e para ter acesso ou não?

http://www.sermilweb.eb.mil.br/rm/processo!input.action

**Comment by wagnerlopes** [comment]
Não, só perfil adm.

2016-07-18 14:32 GMT-03:00 Aryene Campos <notifications@github.com>:

**Comment by 6975usa** [comment]
Resolvido no PR #373 
Esse issue pode ser fechado.
