### ISSUE TITLE
Erro na apresentação - EXAR

### ISSUE THREAD

**Issue by andremb2211** [SERMIL/portal#374]
@6975usa conforme informei para o Sr. durante testes do EXARNET pelo TC Bartz,  o mesmo informou que durante testes na apresentação ocorreu o erro conforme imagem abaixo.
@wagnerlopes 
![erro exar](https://cloud.githubusercontent.com/assets/12534223/16961005/0fc582a6-4dc2-11e6-97e6-299d1088767f.jpg)

**Comment by 6975usa** [comment]
Cel @wagnerlopes 

O Exarnet ta importando uma versao muito antiga do Sermil-core 
Vou ajudar o Sgt @andremb2211 com os ajustes para a importacao da versao mais nova do sermil-core (5.4.4) e resto estará por conta dele.

**Comment by andremb2211** [comment]
@6975usa @wagnerlopes  Realizado tratamento nas mensagens de exceção.

**Comment by 6975usa** [comment]
Cel @wagnerlopes 

Eu ajudei o Sgt Borges a resolver esse problema.
Nao vi nenhum erro de alteracao de sinonimo. 
A servico chama uma NamedQuery que faz uma consulta simples na tabela cidadao que aparentemente nao mudou de nome. 
O que fizemos foi tratar melhor o erro que é mostrado ao cidadao.
Caso sr ache alguma divergencia quanto ao que fizemos favor deletar/alterar o PR #374 

@andremb2211 @fabiosampaio12

**Comment by andremb2211** [comment]
Boa tarde @wagnerlopes,

Esse Issue já foi finalizado, se for possível sugiro que feche o mesmo.

Obrigado.
