### ISSUE TITLE
Alteração campo Deseja Servir

### ISSUE THREAD

**Issue by fabiosampaio12** [SERMIL/portal#375]
O sistema não aceita salvar alteração de Servir (Sim/Não) para municípios não tributários que foram marcados incorretamente, principalmente cidadãos que residem no exterior, que para solicitar o CDI precisam estar marcados como "Não deseja servir". O sistema está exigindo obrigatoriamente um número de CS, porém, não deveria ser obrigatório pois MNT não possui número de CS.
Caminho: CIDADÃO/INFORMAÇÕES/SELEÇÃO
![image](https://cloud.githubusercontent.com/assets/12251958/16986928/b1bbbcea-4e5f-11e6-8cf8-82f871cf29a8.png)

**Comment by wagnerlopes** [comment]
Município não tributário não tem que passar cidadão na seleção.
Para passar cidadão na seleção ele tem que estar vinculado a JSM
tributária, que tem CS.

Em 20/07/2016 9:54 AM, "Ten Sampaio" <notifications@github.com> escreveu:

**Comment by wagnerlopes** [comment]
Depois na distribuição o cidadão vinculado a Jsm não tributaria é perdido,
e gera erro.

Em 20/07/2016 1:19 PM, "Wagner Lopes" <wagner.luis.alopes@gmail.com>
escreveu:

**Comment by fabiosampaio12** [comment]
o campo número de CS está como obrigatório, quando tentamos alterar o campo deseja servir "nao" para cidadãos do Exterior.

**Comment by wagnerlopes** [comment]
Cidadão no exterior não é para preencher esta tela.
Entendam, isso é somente para quem está na seleção!

Em 20/07/2016 1:21 PM, "Ten Sampaio" <notifications@github.com> escreveu:
