### ISSUE TITLE
Fração QCP - CIDADÃO

### ISSUE THREAD

**Issue by fabiosampaio12** [SERMIL/portal#376]
As OM's estão reclamando que não estão conseguindo colocar os militares em suas respectivas frações no QCP pois não está aparecendo mais as frações (conforme tela anexa).
Caminho: Cidadão/Militar/QCP

As frações estão aparecendo na tela OM/Quadro de cargos, porém por lá não é possível fazer o lançamento. 

![image](https://cloud.githubusercontent.com/assets/12251958/16987508/151a8f98-4e63-11e6-9c25-1d2ba86de1d6.png)

**Comment by wagnerlopes** [comment]
Avisa que o recurso está desativado, o Rômulo precisa acertar a tabela QCP
para que tudo volte a funcionar.
Minha ideia era excluir o QCP do SERMIL, muito trabalho e não serve pra
jada. Isso é coisa do Sicapex.

Em 20/07/2016 10:20 AM, "Ten Sampaio" <notifications@github.com> escreveu:
