### ISSUE TITLE
Auditoria de Perfis

### ISSUE THREAD

**Issue by fabiosampaio12** [SERMIL/portal#377]
No menu PAINEL/AUDITORIA DE PERFIS não é possível verificar as alterações que determinado usuário fez no sistema, pois ao clicar sob o CPF é direcionado para tela de liberação e não auditoria de alterações do usuário. (telas anexo)

![image](https://cloud.githubusercontent.com/assets/12251958/16987681/f163e558-4e63-11e6-85a1-672c4367019f.png)

![image](https://cloud.githubusercontent.com/assets/12251958/16987793/69186b78-4e64-11e6-8ca2-6e061eb7af6d.png)

**Comment by wagnerlopes** [comment]
A ideia 3ra facilitar o acesso aos dados do usuário para fazer uma correção
e não chamar as alterações que ele fez.

Em 20/07/2016 10:26 AM, "Ten Sampaio" <notifications@github.com> escreveu:
