### ISSUE TITLE
Alistamento SERMIL  - BRE

### ISSUE THREAD

**Issue by fabiosampaio12** [SERMIL/portal#38]
Após os problemas ocorridos entre alistamentos SERMIL e alistamento ON LINE, foi necessário tirar momentaneamente do portal SERMIL a opção de alistamento, vindo a refletir  nos alistamentos de Brasileiros Residentes no Exterior, que alistam somente pelo SERMIL. Diante da problemática o MRE está solicitando a previsão de data para retorno da opção alistamento ou outro meio para voltar alistar o BRE.

**Comment by wagnerlopes** [comment]
Vamos programar de retomar o alistamento no Portal a partir da versão 5.1.14 que está prevista para ser lançada no dia 29/05. 
O problema que ocorreu pode ter sido resolvido.

**Comment by wagnerlopes** [comment]
Ativei o link do alistamento no Portal.
