### ISSUE TITLE
403.3 - Acesso de escrita negado. Perfil CSM

### ISSUE THREAD

**Issue by aryene** [SERMIL/portal#380]
![csmqc](https://cloud.githubusercontent.com/assets/3015989/17057297/78975bd6-4fef-11e6-9e53-861cf5cf1a16.png)

**Comment by wagnerlopes** [comment]
O QCP esta suspenso ate o Romulo conseguir atualizar a tabela. 
Nao adianta usuarios ficarem mexendo com isso com dados desatualizados.
