### ISSUE TITLE
Níveis de acesso- Nível 4- CSM 

### ISSUE THREAD

**Issue by aryene** [SERMIL/portal#383]
Nível 4- CSM 
OM -> Boletim de Necessidades -> Erro HTTP-403
OM -> Adt Bi Incorporacao -> Erro HTTP-403
OM -> Incorporacao -> Erro HTTP-403
OM -> Vida Militar -> Erro HTTP-403
E para retirar o caminho em que está dando esse erro de acesso do Nível 4- CSM ?
![foto1](https://cloud.githubusercontent.com/assets/3015989/17114038/a0bf88cc-5283-11e6-9721-f9573474f27a.png)

**Comment by wagnerlopes** [comment]
Corrigido versão 5.4.5
