### ISSUE TITLE
CS PERMANENTE SALVADOR - PIS

### ISSUE THREAD

**Issue by fabiosampaio12** [SERMIL/portal#389]
A CS Permanente de Salvador está reclamando que desde a data de ontem, ao salvar os dados no PIS está ocorrendo alguns problemas conforme citado abaixo e imagem anexa:
1. Ao tentar salvar os dados informa que a CS cadastrada está diferente da CS da JSM;
2. Ao salvar os dados no cabeçalho da tela (em azul/branco) some o nome do cidadão aparecendo apenas número de RA;

Peço a gentileza de verificar se está ocorrendo algum BUG no sistema. 

![image](https://cloud.githubusercontent.com/assets/12251958/17225136/11696af4-54da-11e6-9892-a85a3380728b.png)

**Comment by wagnerlopes** [comment]
Ok, tinha um problema na verificação da CS.
Era esse codigo que queria que eles testassem, validando se a cs do cidadao é a mesma da jsm.

**Comment by wagnerlopes** [comment]
Correção feita e já no site. Amanhã vamos ver o retorno da CS.
