### ISSUE TITLE
Perfil CS - Não apresenta a aba painel

### ISSUE THREAD

**Issue by andremb2211** [SERMIL/portal#391]
Durante a criação dos testes do sistema, identificamos no perfil CS que não apresenta a aba painel que permite acessar o próprio cadastro e alterar senha. Teste em produção e local.

@wagnerlopes @6975usa 

![image](https://cloud.githubusercontent.com/assets/12534223/17340382/46ebc0e2-58c6-11e6-9075-099577fd7dbf.png)

**Comment by wagnerlopes** [comment]
Corrigido.
