### ISSUE TITLE
IMPRESSÃO CAM

### ISSUE THREAD

**Issue by fabiosampaio12** [SERMIL/portal#392]
O PRM de Campo Grande- MS, informa os seguintes problemas no SERMIL. 
1. OS CAM ESTÃO SAINDO COM A VALIDADE AINDA PARA 31 DEZ 16, SENDO O CORRETO ESTA VALIDADE APARECER COM A DATA 31 DEZ 17. 

2. AO IMPRIMIR O CAM FOI VERIFICADO QUE O CPF NAO IMPRIME TODA A NUMERAÇÃO E A IMPRESSÃO DO TELEFONE CELULAR FICA FALTANDO OS 2 ÚLTIMOS NÚMEROS, 

 PEÇO A GENTILEZA DE VERIFICAR O TAMANHO DO CAMPO PARA QUE OS DADOS SEJAM IMPRESSOS CORRETAMENTE.

**Comment by wagnerlopes** [comment]
Fiz uma correção, favor verificar se está funcionando no site.
Questão do ano é bem chata, pode ser que ainda não dê certo para alguns casos.
Vamos ver o feedback das JSM.

**Comment by fabiosampaio12** [comment]
Informo que a funcionalidade foi testada e o erro corrigido.

**Comment by wagnerlopes** [comment]
Ok, mas qualquer anormalidade reporta imediatemente.
Não tenho certeza absoluta que servirá para todos os casos que aparecem nas
JSM.
Seria necessário ter o feedback da maioria das JSM, mas isso é quase
impossível.

2016-08-11 12:21 GMT-03:00 Ten Sampaio <notifications@github.com>:
