### ISSUE TITLE
Carta Chamada EXAR -2016 

### ISSUE THREAD

**Issue by fabiosampaio12** [SERMIL/portal#393]
Solicito a possibilidade de corrigir o PERÍODO DE APRESENTAÇÃO que consta na CARTA DE CHAMADA quando esta é gerada pelo sistema.

Este é o texto que está aparecendo:" De acordo com o Regulamento da Lei do Serviço Militar Decreto-Lei N. 57.654, de 20 de janeiro de 1966, Art. 202, o(a) Senhor(a) deverá comparecer à Organização Militar onde foi licenciado(a), no período de 09 a 16 de dezembro de 2015, para a realização do Exercício de Apresentação da Reserva (EXAR).
Deveria ser período de 09 a 16 de dezembro de 2016..........

**Comment by wagnerlopes** [comment]
Fiz uma correção, favor verificar se está funcionando no site.
