### ISSUE TITLE
Acompanhar Alistamento - 

### ISSUE THREAD

**Issue by fabiosampaio12** [SERMIL/portal#394]
Cidadão  RA 161932053630 - FERNANDO ZANELLA, não consegue fazer acompanhamento do alistamento ONLINE. Apresenta a mensagem de erro anexo. 
http://www.alistamento.eb.mil.br/

![image](https://cloud.githubusercontent.com/assets/12251958/17597836/098b3d7c-5fce-11e6-90ac-e8d5f3064e3b.png)

**Comment by wagnerlopes** [comment]
Tenho que olhar o cadastro dele, deve estar inconsistente.

Em 11/08/2016 2:17 PM, "Ten Sampaio" <notifications@github.com> escreveu:

**Comment by wagnerlopes** [comment]
O problema está aqui no cadastro de funcionamento de CS:

05/09/16	06/09/16	- Avenida São Paulo, 1330 ( Grêmio Recreativo Pinhalense ) - Pinhalzinho
02/09/16	05/09/16	- Avenida Rio Grande do Sul, 288 ( Sociedade Esportiva Cedro ) - São Jose do Cedro

Veja que a CS 38 está funcionando de 2 a 5 Set em São Jose do Cedro, e de 5 a 6 em Pinhalzinho, que é o municipio do cidadão em questão, está havendo encavalamento de datas o que NÃO PODE OCORRER.
A CS não pode acabar e começar no mesmo dia em municípios diferentes, senão ocorre erro no agendamento. Isso foi um requisito colocado no início do desenvolvimento deste módulo.
Coloquei a mensagem de erro vista acima exatamente para poder filtrar o erro de datas de funcionamento de CS. Sempre que aparecer a mensagem é problema na data de funcionamento.
Criou um monstro, dia 2 Set é uma sexta e 5 é uma segunda, então a CS volante atende uma sexta, pára no final de semana, continua dia 5 segunda numa cidade e corre pra outra no mesmo dia?
Está muito estranho isso!

@fabiosampaio12 
@6975usa

**Comment by wagnerlopes** [comment]
Solução que adotei:

CSM 16/196 - Sao Jose do Cedro: CS só no dia 02/09 (tirei do dia 5);
CSM 16/193 - Pinhalzinho: CS dia 5 e 6 Set

Arrumei as datas para o dia 5 ficar só com Pinhalzinho.
Pesquisando pelo RA do cidadão já está funcionando.

Toda vez que aparecer o erro:

"Lista de endereço de CS inválida" - é problema de data de funcionamento inconsistente no cadastro.

**Comment by fabiosampaio12** [comment]
Apareceram outros casos. Poderei fazer alteração na data da CS que está conflitante? Caso afirmativo  farei as alterações por aqui, pois já foi agendado as datas de comparecimento dos cidadãos na CS.

**Comment by wagnerlopes** [comment]
@fabiosampaio12 

Pode sim, o que tem que ser feito é identificar na tela de Lista de CS qual o funcionamento que está com as datas encavaladas e fazer o inicio e termino não coincidir.
Isso pode ocorrer nestes casos de CS volante com vários funcionamentos.
Acertando pára de aparecer a mensagem de erro no site.
O objetivo desse erro era justamente identificar o problema.
Veja sempre qual é a CS do cidadão e vá na lista de CS e edita os dados dela.
Vá nos funcionamentos e tente identificar as datas que conflitam.
Se a RM tive preenchido correto era bem mais fácil, mas parece que o pessoal não entendem o mecanismo proposto.

**Comment by fabiosampaio12** [comment]
Ciente.
