### ISSUE TITLE
Inapto Seleção / Excesso de Contingente

### ISSUE THREAD

**Issue by fabiosampaio12** [SERMIL/portal#395]
Alguns PRM estão entrando em contato com o suporte técnico pois vários cidadãos que foram  Inaptos na seleção (Sermil),  estão  recebendo a mensagem para procurar as JSM para solicitação do CDI, porém, ainda constam na situação militar de “Inapto na Seleção” e as JSM não estão fazendo o requerimento pois informam que para requerer o documento devem estar na situação militar de Excesso de Contingente ou Dispensado de Seleção. Existe algum procedimento a ser rodado no banco para que essa situação militar seja alterada? Caso afirmativo, qual a periodicidade desse procedimento ser feito?

**Comment by wagnerlopes** [comment]
Ok, estou alterando periodicamente, pois isso não era uma ação executada
antes da distribuiçao.


Em 15 de agosto de 2016 14:56, Ten Sampaio <notifications@github.com>
escreveu:

**Comment by wagnerlopes** [comment]
Outro detalhe, só estou atualizando o pessoal das CSM dos 9 estados com alisatmento online.
@fabiosampaio12

**Comment by fabiosampaio12** [comment]
Devido a quantidade de solicitações inerentes a alteração da mudança da situação militar dos referidos cidadãos, que consultam os dados e são encaminhados a JSM para requerer o CDI, sem estar na situação militar de Excesso de Contingente,  o TC Mauro Tadeu solicitou se possível priorizar a viabilidade de dar uma prioridade para que esses cidadãos não tomem conhecimento do seu encaminhamento a JSM antes de ser alterado a situação para Excesso de Contingente.

**Comment by wagnerlopes** [comment]
Estou achando estranho que tenha este volume todo, porque o processo de atualizacao tem sido realizado ao final do dia.
Termina o dia, o script roda e passa quem estiver inapto para Excesso, de maneira que no dia seguinte se o cidadão for na JSM ele já estará no excesso.
Não acredito que o cidadão saia correndo da CS direto para a JSM para requerer CDI.
É isso que está ocorrendo???

**Comment by fabiosampaio12** [comment]
Creio que não. Quem está reclamando é o PRM, que esses cidadãos estão aparecendo constantemente na JSM para requerer o documento, porém, se está sendo feito diariamente deve ser coisa antiga. Agradeço a atenção.
