### ISSUE TITLE
BOLNEC  - 1ª RM

### ISSUE THREAD

**Issue by fabiosampaio12** [SERMIL/portal#396]
A 1ªRM fará incorporação do GPT "B" em 01 Nov 16, devido as Olimpíadas, portanto, eles não estão conseguindo lançar o BOLNEC, está bloqueado pois não deram destino aos conscritos distribuídos do GPT "B". Podemos fazer o desbloqueio somente da 1º RM, para que eles consigam lançar o BOLNEC?

**Comment by wagnerlopes** [comment]
Parece piada... uma regra de negócio, ter que ser mudada por causa de
olimpiada.
Só se mudar esses conscritos deles de situação, e deixar em standby em
algum canto aguardando.


Em 15 de agosto de 2016 15:39, Ten Sampaio <notifications@github.com>
escreveu:

**Comment by wagnerlopes** [comment]
@fabiosampaio12 

Veja como está a situação dos ditribuídos da 1 RM no cadastro de 2015:

A = 2887, B = 3940, C = 2, D = 343

Ainda tem muita gente do Gpt A, C e D que as OM da RM não deram destino.
Eu posso mover o Gpt B para uma situação diferente e ficar aguardando chegar a época deles fazerem a incorporação. É só me lembrar de reverter o status do pessoal.
Veja com a RM se eles fazem as OM concluírem a incorporação de março. Pelo jeito lá no RJ a situação está bem complicada com a questão das Olimpíadas.
