### ISSUE TITLE
CS 5ª RM - períodos conflitantes

### ISSUE THREAD

**Issue by fabiosampaio12** [SERMIL/portal#397]
A Comissão de Seleção nº 018 da 5ª RM, que abrange os municípios de Maringá-PR, Tiro-de-Guerra (JSM 015) e Nova Esperança-PR, Tiro-de-Guerra(JSM 209) que consta com período de CS Conflitante, ao alterar o período foi constatado que os cidadãos estão sendo mandados para um único endereço, ou seja, para o TG de Maringá-PR. Os endereços cadastrados são diferentes.

**Comment by wagnerlopes** [comment]
Isso é um problema.
A CS de TG não poderia ser a mesma para TG diferentes.
Cada TG é uma CS, pois são municípios diferentes, cada um com uma JSM
diferente. Assim que foi pensado.
Nesse caso se a RM fez uma CS só, como se fosse volante, para atender
vários TG, com certeza dá confusão.
Faltou orientação as SSMR na montagem dos parâmetros de CS.
Agora tem que ser arrumada uma solução emergencial.

Em 16/08/2016 2:49 PM, "Ten Sampaio" <notifications@github.com> escreveu:
