### ISSUE TITLE
Erro ao gerar GRU pela site alistamento. 

### ISSUE THREAD

**Issue by sgtlima** [SERMIL/portal#398]
Informo que o cidadão RA: 271412132513 - VINICIUS SILVA RODRIGUES FRANCA, ao tentar imprimir a 2º da GRU, para alistamento fora do prazo. Aparece o erro informado na imagem abaixo. 
![erro gru](https://cloud.githubusercontent.com/assets/14078817/17738978/daa652e4-6469-11e6-9768-2db1f63114a2.jpg)

**Comment by wagnerlopes** [comment]
Vou recompilar o relatório da GRU e colocar online.

**Comment by wagnerlopes** [comment]
Corrigido na versão 5.4.6.
