### ISSUE TITLE
CS Online - Ocupação

### ISSUE THREAD

**Issue by fabiosampaio12** [SERMIL/portal#399]
O pessoal da CS Online do 9 GAC está reclamando de erro apresentado na tela  de entrevistas na comissão de seleção , pois constantemente o sistema  está travando no campo OCUPAÇÃO ou, mesmo após inserido, apaga e não deixa finalizar a entrevista, em algumas situações a entrevista tem que ser relançada pois o sistema retorna à fase inicial.

**Comment by wagnerlopes** [comment]
Informa que o campo ocupação é uma lista enorme e demora bastante pra
carregar.
Tudo depende da velocidade da internet deles.
Se tentar salvar a tela antes da carga da lista não dá certo.

Em 17/08/2016 2:00 PM, "Ten Sampaio" <notifications@github.com> escreveu:

**Comment by wagnerlopes** [comment]
Uma opção seria tirar esse campo, não sei se vale a pena essa informação.
Se tiver causando prejuízo ao trabalho era melhor suprir.
O que vale pra distribuição é o padrão de pré qualificação dependendo da
profissão, isso o entrevistador pode perguntar a profissão de lançar logo o
padrão se for o caso, é bem mais rápido.

Em 17/08/2016 3:35 PM, "Wagner Lopes" <wagner.luis.alopes@gmail.com>
escreveu:

**Comment by wagnerlopes** [comment]
Estou aguardando confirmação de @raseng para excluir o campo da Entrevista da CS.

**Comment by wagnerlopes** [comment]
Excluído na versão 5.4.6.
