### ISSUE TITLE
Mostrar zeros iniciais do RA na impressao do CDI

### ISSUE THREAD

**Issue by 6975usa** [SERMIL/portal#4]
Na funcionalidade Impressao de CDI, quando o RA comeca com zero, este zero nao é impresso.

**Comment by wagnerlopes** [comment]
Utilize a funcionalidade de formatar RÁ contida na classe Br.mil.eb.sermil.tipos .Ra que está em sermil-core.

**Comment by 6975usa** [comment]
Resolvido. Vai sair na versao 5.1.13
