### ISSUE TITLE
Mapa de Incorporação - Sem Destino inconsistente

### ISSUE THREAD

**Issue by fabiosampaio12** [SERMIL/portal#400]
O 4º BEC reclama que quando gera o mapa de incorporação SSM8113 (2016) e SSM8113 (2015), aparecem pendencias quanto ao destino do efetivo distribuído para aqueles anos, nestes mapas mostram que existem "Sem Destino" 03 (três) para o ano de 2016 e 01 (um) para o ano de 2015, mas já foram realizados todos os trabalhos quanto à Incorporação, Excesso de Contingente, Refratários. No menu OM, selecionando a opção INCORPORAÇÃO, onde dá destino aos distribuídos não existe cidadão para dar o destino. várias outras OM's estão reclamando da última coluna (sem destino) desse relatório (mapa de incorporação).  

Pergunto: como posso fazer para sanar as pendências desses distribuídos.

**Comment by wagnerlopes** [comment]
Deve ser alguma inconsistência no cadastro do militar, teria que ver com
calma, abrir a consulta SQL do rel, analisar os dados e tentar achar o erro.
Eu estou sem tempo de ver isso.
Além do mais a ideia era o SIG ter assumido isso desde 2015, todos os
relatórios gerenciais.
Ficamos sem o Qlikview, e o SIG não disse a que veio, e já tem 2anos isso!

Em 17/08/2016 3:11 PM, "Ten Sampaio" <notifications@github.com> escreveu:
