### ISSUE TITLE
Cadastrar celular ao invés de telefone no Alistamento Online

### ISSUE THREAD

**Issue by raseng** [SERMIL/portal#403]

**Comment by wagnerlopes** [comment]
Tinha pensado nisso também, vou implementar no alistamento online, apenas cadastrar celular para receber SMS. 
Telefone fixo não adianta de nada.
@raseng

**Comment by raseng** [comment]
Ok. Esta foi a idéia.
Em 22/08/2016 10:04, "Wagner Lopes" <notifications@github.com> escreveu:

**Comment by aryene** [comment]
Cel @wagnerlopes  
Se o senhor não se importa gostaria de fazer essa funcionalidade. 
pergunto se existe alguma regra para ter certeza que  esse numero é de um celular e não de um fixo ?

**Comment by wagnerlopes** [comment]
Implementado.
