### ISSUE TITLE
Confirmação de e-mail no Alistamento Online

### ISSUE THREAD

**Issue by raseng** [SERMIL/portal#404]

**Comment by wagnerlopes** [comment]
Podemos colocar um campo de validação do email (confirmação) para evitar que informe email errado.
Isso no alistamento online? @raseng

**Comment by raseng** [comment]
Sim. Exatamente.
Em 22/08/2016 10:03, "Wagner Lopes" <notifications@github.com> escreveu:

**Comment by wagnerlopes** [comment]
Será incluída na versão 5.4.8, desta forma o cidadão deverá digitar a confirmação do email ao preencher o cadastro.

**Comment by wagnerlopes** [comment]
Concluído.
