### ISSUE TITLE
Erro ao Pesquisar Se arquivo da CS já foi carregado.

### ISSUE THREAD

**Issue by sgtlima** [SERMIL/portal#405]
Erro no sistema em Menu:  Arquivos -> Pesquisar
Ao pesquisar por exemplo com as opções abaixo da o seguinte erro. 
![erro23-08-2016](https://cloud.githubusercontent.com/assets/14078817/17904235/f35e0a86-6944-11e6-8aa5-f6c12cec9a3e.jpg)
ERRO: 
![erro23-08-2016 1](https://cloud.githubusercontent.com/assets/14078817/17904274/1b317afc-6945-11e6-8a31-6fe40e55ad96.jpg)

**Comment by wagnerlopes** [comment]
Erro identificado.
Acertado na versão 5.4.6.
