### ISSUE TITLE
Emissão CDI

### ISSUE THREAD

**Issue by fabiosampaio12** [SERMIL/portal#410]
Estamos recebendo diversas reclamações de usuários do sistema que não estão conseguindo emitir CDI, mesmo o cidadão fazendo jus ao documento está apresentando a mensagem  de erro anexa. 

Situação Militar - Dispensado de Seleção
Evento - Dispensa de Seleção

![image](https://cloud.githubusercontent.com/assets/12251958/18250256/1c15e7c8-7359-11e6-8638-772e0a6b1306.png)

**Comment by wagnerlopes** [comment]
Acabei de falar pró Rômulo que a J ou PRM tem que cadastrar os dados do
CDI  , nr, data, etc, antes de tentar imprimir.
Isso foi um requisito colocado de desde o ano passado. Eles vão ter que
fazer este trabalho.
A situação militar eu acertei, mas os dados do CDi só a JSM tem e pode
colocar.

Em 05/09/2016 11:11 AM, "Ten Sampaio" <notifications@github.com> escreveu:

**Comment by wagnerlopes** [comment]
Confirma pra mim se já está imprimindo o CDI.
Fiz uma correção em 06/07 no código de impressão.

**Comment by 6975usa** [comment]
Isso ja tinha sido corrigido h'a muito tempo.
Ja estava funcionando faz tempo. Esquisito apresentar esse erro.
Vou dar uma olhada 2Feira e te informo o que aconteceu @fabiosampaio12

**Comment by wagnerlopes** [comment]
Já está ok. Acertei ontem o problema e coloquei no ar.
São essas diversas atualizações que temos que ir fazendo correndo que acabam corrompendo o codigo que está estável.

**Comment by wagnerlopes** [comment]
@6975usa Nem mexe mais para não aparecer mais problema nesse CDI.
Até vocês chegarem a um acordo com o Certificado unico temos que ir vivendo com esse monte de certificados no sistema. 
Ontem fiquei um bom tempo com o Aquino no Whatsapp até descobrir onde está o problema que os Delegados estavam relatando.
Agora está funcionando e todo mundo está imprimindo CDI por ai.

**Comment by 6975usa** [comment]
@wagnerlopes Sim Sr
