### ISSUE TITLE
Carta Chamada EXAR -2016 

### ISSUE THREAD

**Issue by fabiosampaio12** [SERMIL/portal#411]
A carta de chamada do EXAR está apresentando erro nas datas de apresentação EXARNET. 

![image](https://cloud.githubusercontent.com/assets/12251958/18287294/f24509f2-744c-11e6-82e5-4a45e4e74f57.png)

**Comment by wagnerlopes** [comment]
Já tinha consertado isso, parece que houve perda sincronismo no github.
Tem que ajustar de novo.

Em 06/09/2016 4:15 PM, "Ten Sampaio" <notifications@github.com> escreveu:

**Comment by wagnerlopes** [comment]
@6975usa Esse aqui é outro, também tinha acertado a data a 1 mes atras e voltou o problema.
Perda de sincronismo na atualização do repositorio do GitHub.

**Comment by wagnerlopes** [comment]
Corrigido. @fabiosampaio12
