### ISSUE TITLE
Arrimo CS

### ISSUE THREAD

**Issue by fabiosampaio12** [SERMIL/portal#414]
Recebemos várias reclamações de cidadãos que estão procurando as JSM por estarem aptos na seleção, porém,  na condição de "Arrimo", e o sistema não disponibiliza a impressão de CDI para os mesmos. Na entrevista consta preenchido a situação de arrimo, porém no tipo de dispensa (tela alistamento) consta sem dispensa. 
![joao pedro0](https://cloud.githubusercontent.com/assets/12251958/18437479/812107fe-78d3-11e6-995b-567d7a4966ae.JPG)
![joao pedro1](https://cloud.githubusercontent.com/assets/12251958/18437478/811d5adc-78d3-11e6-8c0f-caaa56867834.JPG)

**Comment by wagnerlopes** [comment]
Ok, durante a migração da tela de entrevista para a versão nova, faltou
atualizar os que já estavam na situação de arrimo.
Vou acertar o banco via SQL e verificar se não tem outro problema.
A impressão do CDI complicou bastante após alteração do processo, antes
todos cdi eram emitidos no Sasm, com averbação direta do módulo CS.
Agora o processo pulverizou a emissão.
Faltam alguns ajustes para ficar correto.

Em 12/09/2016 10:27 AM, "Ten Sampaio" <notifications@github.com> escreveu:

**Comment by wagnerlopes** [comment]
Fiz o ajuste no banco.
Veja que os cidadãos estão com a situação e a dispensa coretos, com o evento excesso incluído.
Agora vai aparecer o erro de que o cidadão não tem a lista de certificados.
A JSM deverá providenciar o cadastramento dos dados do CDI na ficha do cidadão antes de tentar imprimir o certificado, dados do CDI eu não tenho para inserir automaticamente para cada cidadão.
Façam o teste com o RA acima para ver o erro que aparece.
@fabiosampaio12

**Comment by fabiosampaio12** [comment]
Fiz os testes. De acordo com a regra de negócio, está correto o sistema exigir o cadastramento dos dados  de um certificado para que seja impresso. Desde já agradeço.
