### ISSUE TITLE
Certificado Simplificado: CDI formato único

### ISSUE THREAD

**Issue by 6975usa** [SERMIL/portal#416]
Criar CDI no formato unico

**Comment by 6975usa** [comment]
Caro Cel @wagnerlopes 

Dois assuntos com o senhor:

1) Para criacao do CDI no formato unico preciso que seja criado na tabela CID_CERTIFICADO um campo chamado FUNCAO_DO_RESPONSAVEL varchar(50) DEFAULT NULL . 
O detalhe disso o sr pode no CDI anexo.
Esse foi o modelo implantado exatamente igual à sua Portaria de Criação.

2) O Cap Pantoja criou o segundo documento anexo, excelente trabalho por sinal, e quanto a esse documento pergunto se o sr implementou alguma na base de dados.
O motivo dessa pergunta é que estou pronto para entregar o CDI no formato unico, mas taves fosse mais interessante mostrar o motivo no campo do CDI chamado Situacao Militar.

Grato 

[CDI Formato Unico.pdf](https://github.com/SERMIL/portal/files/482704/CDI.Formato.Unico.pdf)

[Uploading REQUISITO SERMIL DOCUMENTO MILITAR.docx…]()

Para conhecimento: @raseng @fabiosampaio12 @romulodba

**Comment by wagnerlopes** [comment]
Ok, era isso mesmo que deveria ser feito.
O campo na tabela cid_documento posso incluir facilmente, a pergunta é se
vale a pena guardar essa informação, como é um campo livre, vão escrever
milhões de abobrinhas diferentes, por extenso, abreviado, etc, e depois não
serve para grande coisa. A pessoa que assinou já vamos ter, inclusive
poderia ligar com o usuário na tabela Usuário pelo CPF.
O segundo documento no email não veio, mas acho que é o mesmo que estou
modelando e que enxuga situação, evento e dispensa na modelagem. Esse exige
uma abordagem mais profunda que estou estudando.

Em 20/09/2016 10:59 AM, "Anselmo S Ribeiro" <notifications@github.com>
escreveu:

**Comment by 6975usa** [comment]
![cameletronico_final_limpo](https://cloud.githubusercontent.com/assets/6667748/18675328/651d921a-7f28-11e6-98de-b45cfabc5b22.jpg)


Realmente o modelo da Portaria nao fala sobre funcao da autoridade que assina, conforme o sr pode ver no modelo acima. Realmente podemos esquecer isso.

Mas ainda permanece o fato de que o campo "Autoridade Resposavel pela emissao", que é a autoridade que assina, é um campo livre. Existe um jeito de pegar esse nome de algum outro lugar?

**Comment by wagnerlopes** [comment]
No caso do CAM coloquei a função na tabela jsm_info, talvez fosse o caso de
generalizar e colocar em usuario para que quem assina configurar a função e
o processo buscar o nome, posto e função tudo na tabela Usuário. Funciona?

Em 20/09/2016 11:53 AM, "Anselmo S Ribeiro" <notifications@github.com>
escreveu:

**Comment by wagnerlopes** [comment]
@6975usa @romulodba @raseng 

Terminei de implementar no banco de dados as alterações referentes ao Certificado Único.
Mudanças:

## Tabela CID_CERTIFICADO
* Coluna RESPONSAVEL não utilizar, vou retirar da tabela num passo futuro;
* Adicionei coluna USUARIO_ASSINATURA para inserir oo CPF de quem assina o certificado;
* Coluna AUDITORIA_USUARIO é o cpf de quem cadastrou ou fez modificação no certificado;
* Coluna AUDITORIA_DATA é a data de alguma altereção realizada.

## Tabela USUARIO
* Adicionei a coluna FUNCAO_DESCRICAO para colocar a função de quem assina o certificado.

Realizei as mudanças nas entidades do modelo CidCertificado e Usuario incluindo os atributos que foram adicionados ao modelo de dados.
Está tudo comitado no GitHub na organização como versão 5.4.7 .
Atentar para o cabeçalho das classes, sempre estou alterando o @version para refletir a versão em que fiz alguma alteração na classe, no caso se tiver 5.4.7 é a classe que acabei de mexer. Sugiro que todos alterem o numero da versão, coloquem o nome no @author se não tiver, assim podemos saber quem fez alguma coisa e em qual versão.
Precisa alterar as telas de cadastro de usuario para colocar a caixa de texto de função, Usuarioservico para salvar a informação.
Precisa alterar a tela de cadastro de certificado e o serviço correspondente.
Usar a versão 5.4.7, já fiz muita mudança nessas classe, se usar versão antiga, vai dar problema de conflito de versão ou vamos perder código!

**Comment by 6975usa** [comment]
Criei um tipo certificado geral com os seguintes campos:

public class Certificado {
   private String validade;
   private String tipo;
   private String ra;
   private String cpf;
   private String nome;
   private String nomeDaMae;
   private String nomeDoPai;
   private String nascimentoLocal;
   private Date nascimentoData;
   private String situacaoMilitar;
   private String informacoes;
   private Date expedicaoData;
   private Usuario autoridadeResponsavel;
}

Preencho todos os valores e mando para para RelatorioAction imprimir o CDI pra  mim.
Nao trabalhei com SQL, to mandando o tipo Certificado pronto e todo preenchido.
Em autoridadeResponsavel mando o Usuario. La no jasper chamo a propriedades nome e funcaoDescricao para exibir.

Reparei tb que nao preciso redirecionar para RelatorioAction, so chamo o metodo estatico printRel.

**Comment by wagnerlopes** [comment]
Ok! Usando o objeto fica bem melhor!

Em 26/09/2016 4:48 PM, "Anselmo S Ribeiro" <notifications@github.com>
escreveu:

**Comment by wagnerlopes** [comment]
Versão final do Certificado Simplificado (CDI) está finalizada.
Impressão de CDI será realizada apenas no formato único. 
Usuários deverão ser avisados.
Versão 5.4.7 deverá entrar em produção em 30/09/2016.
@6975usa @fabiosampaio12 @andremb2211 @romulodba @raseng

**Comment by romulodba** [comment]
Copiado!



*[image: Início]Prof. Rômulo Santos*www. <http://www.dominandoti.com.br>do
<http://www.dominandoti.com.br>minandoti.com.br
<http://www.dominandoti.com.br>
*A melhor** p**reparação para concursos na área de tecnologia da
informação.*

Em 27 de setembro de 2016 20:04, Wagner Lopes <notifications@github.com>
escreveu:

**Comment by romulodba** [comment]
Cel Abreu levantamos alguns ajustes hoje no CDI e sugiro "como forma de
assessoramento" que o Anselmo deixe o senhor inteirado da situação antes de
lançar a versão 5.4.7.

Agradeço os ouvidos!!!



*[image: Início]Prof. Rômulo Santos*www. <http://www.dominandoti.com.br>do
<http://www.dominandoti.com.br>minandoti.com.br
<http://www.dominandoti.com.br>
*A melhor** p**reparação para concursos na área de tecnologia da
informação.*

Em 27 de setembro de 2016 20:06, Romulo Ferreira dos Santos <
romulodba@gmail.com> escreveu:

**Comment by 6975usa** [comment]
Cel @wagnerlopes 

O novo CDI foi apresentado hoje para o TC Aquino e o PRM e eles apontaram algumas possibilidades de melhoria:
1) Como ja ha alguns CDI cadastrados, validar se o CDI tem responsavel cadastrado antes de imprimirl
2) Retirar do cadastro do CDI: Serie, Numero, OM e Motivo.

Pediram florzinha tambem:
3) Colocar o botao Imprimir em cada CDI da lista de Certificados.

E' preciso analisar o impacto disso, principalmente 1 e 2 para os outros Certificados que nao sao CDI.

@romulodba @raseng @andremb2211

**Comment by 6975usa** [comment]
As outras coisas que foram faladas dizem respeito aquela tabela do Cap Pantoja.
Me limitei a dizer que o Sr ja iniciou a implantacao disso, mas que o CDI inicialmente nao vai contemplar essas funcionalidades. Nao nessa versao que pretendemos lancar ate o dia 30

**Comment by wagnerlopes** [comment]
Corretas as observações!

* A planilha de situações do Pantoja já tem o modelo de dados implementado no BD, inclusive com os dados importados, mas demanda ajustes em diversos procedimentos para que se torne funcional e possa ser utilizada no certificado, tem que ser revistos todos os relatórios, módulos PL/SQL e o código Java das aplicações pois está sendo alterado os códigos dos domínios conforme encaminhei no e-mail para os usuários, peço que validem os códigos das situações e digam se está tudo correto ou falta alguma coisa;
* A coluna responsável em CID_CERTIFICADO deve ter muita "abobrinha" cadastrada uma vez que é uma string de livre digitação, no modelo novo de certificado estamos implementando a chave estrangeira via CPF da tabela de usuários que evita entrar informação inútil, então acho que não se aproveita grande coisa da coluna responsável atual para lançar no CDI;
* As colunas serie, numero, OM e motivo vou retirar do modelo de dados novo, a tabela atual não vamos mexer para não dar problema em algum ponto do sistema mas vamos ignorar a gravação de dados nessas colunas, para referência a tabela atual é CID_CERTIFICADO e a nova está como CID_CERTIFICADO_2 mas estou pensando em renomear para CID_DOC_MILITAR uma vez que tem CAM, CDI, Certidão, Reservista tudo cadastrado nela, mas ainda não migrei os dados pois envolve a modelagem nova om os códigos da planilha do Pantoja.
@6975usa @romulodba @andremb2211 @raseng @Maurotadeu

**Comment by 6975usa** [comment]
Cel @wagnerlopes 
Nao entendi muito bem  o 2º item da observacao do Sr acima.
A coluna observacao em CID_CERTIFICADO ´e bem nova e nao contem dados ainda. Segundo o que me lembro do que foi feito. 
E todo dado, ou seja, cpf que esta' sendo inserido nela e' validado antes. 
Entao respeitosamente pergunto: como ela pode conter abobrinha? (duvida real. Nao e ' questionamento)
Essa coluna é essencial para que coloquemos o nome e a funcao de quem assina o CDI.

Quanto a retirado das dos campos serie, numero, OM e motivo sou absolutamente a favor. Realmente eles estao desnecessarios.

Se o sr puder fazer um PR pro meu git quando acabar essas mudancas vai ser otimo. Assim poderei comecar os trabalhos com o CAM. 
Caso o sr queira que eu implemente tb vai ser bom pois posso faze-lo em conjunto com o Sgt @andremb2211  .

Grato

**Comment by wagnerlopes** [comment]
Não tem coluna OBSERVACAo em CID_CERTIFICADO, temos MOTIVO e RESPONSAVEL.


Em 28 de setembro de 2016 08:57, Anselmo S Ribeiro <notifications@github.com

**Comment by 6975usa** [comment]
Me referia a coluna RESPONSAVEL mesmo. Realmente ela tem muita abobrinha conforme eu vi no banco. Mas essa coluna agora so ta inserindo CPFs validados.

**Comment by wagnerlopes** [comment]
Agora, mas ela contém dados desde a integração do SERMIL com SISCSM, e
também dados que vêem do SASM VIA arquivo de averbação que os secretários
carregam todos os dias. Por isso ela contém tantas informações diferentes.

Em 28/09/2016 9:22 AM, "Anselmo S Ribeiro" <notifications@github.com>
escreveu:

Me referia a coluna RESPONSAVEL mesmo. Realmente ela tem muita abobrinha
conforme eu vi no banco. Mas essa coluna agora so ta inserindo CPFs
validados.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/SERMIL/portal/issues/416#issuecomment-250151286>, or mute
the thread
