### ISSUE TITLE
Bloqueio do BOLNEC

### ISSUE THREAD

**Issue by fabiosampaio12** [SERMIL/portal#417]
Segundo o calendário de obrigações do Serviço Militar o prazo para lançamento do BOLNEC pelas OM finalizou dia 16/09  e estamos na fase de auditoria pelas RM. Peço a gentileza de verificar possibilidade de bloqueio de alteração do mesmo pelo nível OM, pois as RM estão fazendo as alterações necessárias e ainda continua aberto para OM's .

**Comment by wagnerlopes** [comment]
Vou providenciar.

Em 21/09/2016 2:18 PM, "Ten Sampaio" <notifications@github.com> escreveu:
