### ISSUE TITLE
Erro no carregamento dos arquivos bancários de taxa e multas

### ISSUE THREAD

**Issue by andremb2211** [SERMIL/portal#427]
Bom dia Cel @wagnerlopes,

Estou realizando testes de carregamento em ambiente local,  do modulo de retorno bancário de taxas e multas conforme pedido do cap @romulodba.

Realizei o carregamento de 3 arquivos de cada (taxa e multa).

Em todos os testes apresentou o erro conforme imagem abaixo.

Enviei no email do Sr. os arquivos que realizei os testes.

![image](https://cloud.githubusercontent.com/assets/12534223/19351637/f5623706-9132-11e6-922e-619c15a3e64a.png)

@6975usa @aryene

**Comment by wagnerlopes** [comment]
Vou usar os arquivos que mandou e realizar o debug de onde está ocorrendo o erro.
Eu tinha somente 4 arquivos gerados no dia 13 set, vamos ver o que tem de diferentes nesses que me mandou.
@andremb2211

**Comment by wagnerlopes** [comment]
Só de abrir o arquivo de retorno da Caixa já percebi o erro.
Existem linhas em branco entre cada registro de pagamento,, o que não acontecia no arquivo anterior.
Exemplo:
`
A2610017              COSEMI TAXA MILITAR 104CAIXA ECON. FEDERAL 2016101200434603                                                                     

G0875006009000035    2016101120161014867500000000000008943560000000000000030843950000000018050000175000000010231    1                       1         

G0875006009000035    2016101120161014867100000000000008943560000000000000010513080000000013480000175000000020186    1                       1         

G0875006009000035    2016101120161014867100000000000008943560000000000000010513080000000003130000175000000031435    1                       1        
`

Não sei se isso sempre ocorrerá, não previ o tratamento para o caso das linhas em branco, pode ser que houve algum erro no programa cliente ao baixar do site da Caixa.
Vou alterar o código para evitar a leitura de linhas que estejam sem dados.

@andremb2211 @6975usa @romulodba

**Comment by wagnerlopes** [comment]
Corrigido.

**Comment by andremb2211** [comment]
Cel @wagnerlopes realizei mais alguns testes com base na documentação que  senhor me enviou.

Fiz um teste carregando o arquivo sem a linha que contem a quantidade "Total de registros" e "Total de arrecadação" e apresentou o erro abaixo. Fiz um teste sem o cabeçalho e está validando corretamente.

![image](https://cloud.githubusercontent.com/assets/12534223/19529412/83f11106-960e-11e6-9896-95504470884f.png)

**Comment by wagnerlopes** [comment]
Ok.
A linha final Z eu não validei a existência, assumi a premissa que vai
existir.
É um erro remoto, nas que pode ocorrer.
Vou incluir a validação pra versão futura.
Por agora já está ótimo.
Vamos terminar os testes que nosso tem está acabando.

Em 19/10/2016 3:13 PM, "Borges" <notifications@github.com> escreveu:

**Comment by andremb2211** [comment]
Entendido Cel @wagnerlopes.

@romulodba @aryene @6975usa
