### ISSUE TITLE
Teste e validação de Guia de Arrecadação Taxa/Multa

### ISSUE THREAD

**Issue by andremb2211** [SERMIL/portal#429]
Boa tarde Cel @wagnerlopes,

Estou realizando testes na gru e identifiquei duas situações.

1 - Nas guias da CEF e correios não estão apresentando o artigo no qual a gru foi gerada.

![image](https://cloud.githubusercontent.com/assets/12534223/19446970/2bb7b476-947a-11e6-8d2d-445348a02f27.png)

2 - No momento de geração da guia do BB não apresenta os campos de artigo e tarifa bancaria
Se trata de erro ? 

![image](https://cloud.githubusercontent.com/assets/12534223/19447086/acba489a-947a-11e6-8bad-b4a1802182d4.png)

@romulodba @aryene @6975usa

**Comment by wagnerlopes** [comment]
GRU é uma coisa. Boleto da CEf e Correio outra.

Não entendi porque voce esta olhando Boleto e tratando de GRU, o layout do
formulario é compeltamente diferente.



Em 17 de outubro de 2016 15:02, Borges <notifications@github.com> escreveu:

**Comment by andremb2211** [comment]
Cel @wagnerlopes  realmente fiz uma confusão.

Peço que o considere somente a questão do boleto CEF/CORREIOS não está apresentando o artigo.

**Comment by wagnerlopes** [comment]
Ok, erro.
Estou submetendo uma alteração no código, voce vai baixar do github e
sincronizar sua maquina para continuar a testar.


Em 17 de outubro de 2016 15:52, Borges <notifications@github.com> escreveu:

**Comment by wagnerlopes** [comment]
Aguardando retorno da Equipe de Homologação da CEF quanto ao formato do boleto e código de barras.
Solicitado em 13 set 16.

**Comment by andremb2211** [comment]
Cel @wagnerlopes baixei as alterações da maquina do sr e realizei os testes.

Identifiquei que no formulario da cef/correios o campo de artigos nao está sendo carregado.


![image](https://cloud.githubusercontent.com/assets/12534223/19520923/9fb1009a-95f0-11e6-9edd-ef991e5bfe25.png)

**Comment by wagnerlopes** [comment]
Corrigi a carga da lista, via javascript.
Está na organização.
Esta página ainda será muito alterada, estou modificando o módulo de registro de taxas/multas.

**Comment by andremb2211** [comment]
Cel @wagnerlopes o senhor acha melhor então eu esperar o senhor realizar todas as modificações para depois realizar as validações?

**Comment by wagnerlopes** [comment]
Não dá tempo Borges.
Vou demorar mais de um mês até finalizar tudo.
Temos que colocar a versão 5.4.7 no ar na sexta.
O resto vai ficar para outras versões.

2016-10-19 13:59 GMT-02:00 Borges <notifications@github.com>:

**Comment by wagnerlopes** [comment]
Fiz a correção da emissão do boleto bancário, está na organização.
@andremb2211

**Comment by andremb2211** [comment]
Cel @wagnerlopes ja baixei  e realizei os testes. A Geração está ok.

Conforme pedido do cap @romulodba vou realizar o pagamento dos mesmos.

**Comment by andremb2211** [comment]
Cel @wagnerlopes 

Realizei o pagamento dos boletos e estão ok.

Testes finalizado.

@romulodba @6975usa @aryene

**Comment by wagnerlopes** [comment]
Vamos verificar amanhã no arquivo da CEF que o Ten Arai baixar se aparece o
pagamento.
Faça uma busca pelos números  código de barras pra ver se acha o registro
do pagamento.

Em 20/10/2016 2:50 PM, "Borges" <notifications@github.com> escreveu:

Cel @wagnerlopes <https://github.com/wagnerlopes>

Realizei o pagamento dos boletos e estão ok.

Testes finalizado.

@romulodba <https://github.com/romulodba> @6975usa
<https://github.com/6975usa> @aryene <https://github.com/aryene>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/SERMIL/portal/issues/429#issuecomment-255162926>, or mute
the thread
