### ISSUE TITLE
Mensagem Alistamento ONLINE

### ISSUE THREAD

**Issue by fabiosampaio12** [SERMIL/portal#432]
Cidadão que foi Inapto na CS, ao acompanhar alistamento está aparecendo mensagem para ir na comissão de designação (tela anexo), onde deveria ser encaminhado para JSM. O TC Aquino pediu para o senhor verificar e qualquer dúvida entrar em contato com ele. Desde já agradeço a atenção. 

![image](https://cloud.githubusercontent.com/assets/12251958/19516338/430f54f6-95da-11e6-9700-d0736eea2b7d.png)

**Comment by wagnerlopes** [comment]
A mensagem é para ir caso não possua CDI, o problema é que está dificil de
separar o pessoal que vai ser dispensado pela distribuição daqueles que
estão pegando CDI agora, ou seja quem esta inapto.
Ficou muito confuso o processo.
Coloquei para ir somente se não possuir CDI, para tentar separar desses que
estão indo agora.


Em 19 de outubro de 2016 09:01, Ten Sampaio <notifications@github.com>
escreveu:

**Comment by wagnerlopes** [comment]
* Mensagem foi alterada para o caso dos Inaptos (diagnóstico não pode ser vazio!);
* Registrar aqui todas as situações anômalas encontradas e as mensagens desejadas.

@fabiosampaio12 @raseng @andremb2211 @romulodba @6975usa

**Comment by fabiosampaio12** [comment]
Verificado e as novas atualizações foram confirmadas nas consultas.
