### ISSUE TITLE
Taxas e Multas emitidas pelo SERMILMOB

### ISSUE THREAD

**Issue by fabiosampaio12** [SERMIL/portal#439]
Vários secretários de JSM estão relatando problemas com códigos de barra dos boletos e GRU emitidos pelo SERMILMOB, conforme relata a secretária abaixo: 

_"Sou Veroni, Secretária da JSM 07/288-Senador Canedo-GO, venho informar por meio deste, que está ocorrendo um erro nos códigos de barras dos boletos emitidos pelo sistema SERMIL para pagamento de taxas e multas, conforme os usuários e também as instituições bancárias, tanto Caixa Econômica Federal quanto Banco do Brasil, falta um número no código de barras, por este motivo, não é possível realizar a cobrança dos valores emitidos. No caso da CEF, simplesmente não passa o código de barras. Já no Banco do Brasil, quando o boleto é emitido, se houver um número zero no final do valor, não sai na impressão, e quando o cidadão vai pagar, passa apenas dez por cento do valor da multa. Por exemplo, uma multa de refratário no valor de R$ 19,80, quando passa o código de barras debita apenas R$ 1,98."

Certa de de vossa atenção, agradeço.

Atenciosamente;

Veroni Isabel Marques Gonçalves de Oliveira
Secretária da JSM 07/288
Senador Canedo-GO

**Comment by wagnerlopes** [comment]
Quanto ao boleto da CEF, a equipe de homologação da própria CEF informou via e-mail ao TC Aquino que estava tudo correto no código de barras, o Cap Romulo mandou o Borges fazer um pagamento no terminal e disse que pagou. Eu confiei que estava tudo certo, agora não passa nos terminais.
Na GRU vou verificar e parece que os usuarios não estão digitando todos os números, o zero no final tem que ser digitado também. Vou melhorar a máscara para evitar esse problema. Confusão de usuário.
@fabiosampaio12 @romulodba @andremb2211 @raseng

**Comment by wagnerlopes** [comment]
Fiz uma correção na GRU.
No boleto, não sei qual foi o problema, aparentemente está de acordo com as normas da CEF.
Preciso de mais informações para poder verificar.

**Comment by andremb2211** [comment]
Bom dia cel @wagnerlopes após todos os ajustes que o senhor fez gerei os boletos em anexo e realizei o pagamento.

o cod. de barras foi gerado correto.

No momento do pagamento inclusive questionei a atendente se o sistema da cef havia reconhecido o cod de barras e ela me respondeu que havia reconhecido normalmente.

[CEF.pdf](https://github.com/SERMIL/portal/files/556095/CEF.pdf)
[CEF.pdf](https://github.com/SERMIL/portal/files/556109/CEF.pdf)



@romulodba @6975usa @aryene

**Comment by wagnerlopes** [comment]
Estou acertando caso a caso.


Em 27 de outubro de 2016 09:07, Ten Sampaio <notifications@github.com>
escreveu:

**Comment by wagnerlopes** [comment]
Fiz correção que se o CPF fosse digitado com menos de 11 digitos poderia apresentar erro.
