### ISSUE TITLE
Relatório 8129 

### ISSUE THREAD

**Issue by fabiosampaio12** [SERMIL/portal#441]
Verificar o relatório 8129 SERMIL, pois fomos informados que o mesmo está sem ser alimentado desde junho 2016. 

[relatorio 8129.pdf](https://github.com/SERMIL/portal/files/558541/relatorio.8129.pdf)

**Comment by wagnerlopes** [comment]
O Rel 8129 foi feito errado.
O SQL fazia join de Cidadão com Ocupação, sendo que a coluna ocupação é opcional em Cidadão.
Como não estamos mais coletando ocupação no alistamento, todos os cidadãos sem código de ocupação não aparecendo no relatório.
Alterei a consulta para fazer um LEFT OUTER JOIN entre Cidadao e Ocupacao.
Assim todos aparecem no relatório.
