### ISSUE TITLE
Melhoria no módulo TAXA E MULTAS 

### ISSUE THREAD

**Issue by sgtlima** [SERMIL/portal#447]
A pedido do Cel Aquino/ Ten Alexandre Silva abro uma solicitação para melhoria no Sermil. 

 

1.  -> **No Menu Cidadão -> Guia de Arrecadação** 
      ->   Foi pedido para que vinculasse ao CPF ao Cidadão. 
      ->   Após ser lançando nesta aba, a taxa já deverá esta lançada no cadastro do cidadão, ao pesquisar o mesmo. 

2) -> **No cadastro do Cidadão -> Informações -> Arrecadação de Taxa e Multas** 
    ->  Ao clicar no botão Adicionar -> A pagina aberta deverá já ter todos os dados para preencher (Igual quando clica no botão gerar boleto). Assim evitando duas telas. 
  
3) -> **No cadastro do Cidadão -> Informações -> Arrecadação de Taxa e Multas** 
    -> O Ten Arai irá carregar os arquivos bancários no Sermil, onde poderá ser verificado o pagamento das taxas e multas. Foi solicitado que ao lado do botão onde hoje aparece  **gerar boleto**, seja adicionado um campo informando que o pagamento foi efetuado.

**Comment by wagnerlopes** [comment]
OK, @raseng @Maurotadeu

Estive considerando essas ações.
O número 3 eu já fiz, toda vez que o pagamento é carregado aparece um logo onde são verificadas as informações do pagamento. Mas não está aparecendo ainda porque existem alguns detalhes para que isto aconteça quanto aos boletos. Vejam o teste no RA 190182046689 na aba de Arrecadações.
O problema é que tenho que identificar qual a taxa que foi paga, coloquei no boleto da CEF/Correios um campo com o número, data e cpf da taxa paga para poder identificar na volta. Os boletos impressos não tem estas informações, então não consigo identificar a taxa/multa paga nem quem é o cidadão. Quando todas as taxas/multas forem pagas com boletos gerados pelo sistema isto estará resolvido.
A GRU do Banco do Brasil é outro problema, lá não tem espaço no código de barras para colocar data, cpf e o número da tax/multa paga, o que esta dificultando bastante essas identificação. São muitos detalhes técnicos quando se trabalha com vários modelos de documentos.
o número 1 eu não vinculei direto com o CPF do cidadão porque iria engessar muito a geração da guia, ou seja, o secretário teria que alistar/cadastrar primeiro o cidadão no sistema para depois poder gerar uma guia, não sei se é isso que eles fazem, pode ser que antes de alistar peçam para o cidadão pagar a guia da multa. Talvez gerasse reclamação das JSM alegando que está prejudicando o trabalho. Precisa ser averiguado.
O numero 2 coloquei um link na página depois de salva a taxa/multa onde clicando chama a tela com os dados preenchidos para gerar o boleto/gru, ficando somente pendente o usuario dizer qual o banco que vai pagar e o valor da tarifa, isso é definido na hora.
São essas as considerações. Ainda tudo é protótipo. Esta em melhoria constante.
