### ISSUE TITLE
Erro ao carregar arquivo BCC e IAP 

### ISSUE THREAD

**Issue by sgtlima** [SERMIL/portal#448]
![erro 17112016](https://cloud.githubusercontent.com/assets/14078817/20389959/81f1876c-acb3-11e6-93ec-b4e21c8cfb13.jpg)

Ao tentar carregar os arquivos no Menu --> Resultado de BCC/IAP 
Aparece a seguinte mensagem de erro.

**Comment by wagnerlopes** [comment]
Preciso do arquivo bcc/iap, pode enviar @sgtlima ?

**Comment by sgtlima** [comment]
Cel enviei para o email do Senhor. 
wagner.luis.alopes@gmail.com

**Comment by wagnerlopes** [comment]
Fiz uma correção no processamento para apresentar a mensagem de erro, mas ainda não atualizei a aplicação.
Forem enviados tres arquivos, eu processei por aqui dois, que tinham erros de leitora optica internos em alguns registros. O terceiro esta completamente invalido, o nome é CS004-10BCC, precisa refazer na leitora optica da 10 RM.
Os outros já estão carregados. (CS003-04IAP e DADOCS0401IAP).
@sgtlima
