### ISSUE TITLE
Distribuição TG Divinópolis 

### ISSUE THREAD

**Issue by fabiosampaio12** [SERMIL/portal#458]
Conforme consta na relação anexo, os conscritos distribuídos para TG de Divinópolis vieram da JSM 12/077	GOVERNADOR VALADARES e não da JSM 11/079 - DIVINOPOLIS. Peço a gentileza de verificar e caso seja possível, encaminhar os cidadãos distribuídos erroneamente para Divinopolis para Excesso de Contingente, pois o TG de Governador Valadares recebeu os conscritos corretamente, sendo assim, a RM vai fazer a distribuição manual para o referido TG. 
[tg divinopolis.pdf](https://github.com/SERMIL/portal/files/661569/tg.divinopolis.pdf)

**Comment by fabiosampaio12** [comment]
Foi verificado que a OM está cadastrada com município errado (anexo).
![whatsapp image 2016-12-19 at 14 52 11](https://cloud.githubusercontent.com/assets/12251958/21322041/823488be-c5fe-11e6-923c-f2479d2849f1.jpeg)

**Comment by 6975usa** [comment]
Curz Credo !
Nao entendi nada.

O caso é o seguinte:

**PROBLEMA**: O TG de Divinopolis recebeu conscritos de Governador Valadares 

**MOTIVO**: O TG de Divinopolis cadastrou no Sermil o seu endereco em Governador Valadares. 

**SOLUCAO**: Se o TG de Divinopolis deseja receber conscritos de Divinopolis, entao que cadastre no Sermil o endereco de Divinopolis. A RM deve: 1) Por na reserva os conscritos de Gov Val que foram distribuidos para esse TG. 2) Distribuir os conscritos de Divinopolis para esse TG. **Manualmente**.

**Comment by wagnerlopes** [comment]
Isso ocorre porque a distribuição de TG, como todos os conscritos veem da mesma JSM de apenas um Município, a distribuição pega o código do Município do TG na tabela OM  e acha a JSM com aquele codigo de Municipio, depois pega os aptos na tabela cidadão vinculados com aquela JSM.
Se fizerem a vinculação errada de município no sistema, lógico que vai dar erro.
Será que a pessoa não consegue nem registrar o nome do município onde está localizado seu TG? É pedir muito? Será que consegue fazer um cadastro de compra em uma loja sem errar o local onde mora???

**Comment by wagnerlopes** [comment]
A situação da JSM 11/079 Divinópolis é a seguinte, 817 indicados para o TG estão no Excesso de Contingente.
Vou cancelar a distribuição do pessoal da JSM 12/077 Gov Valadares para o TG 04/019, para evitar mais confusão.

**Comment by wagnerlopes** [comment]
@fabiosampaio12 @Maurotadeu @raseng @romulodba 

Acertei o problema do TG 04/019 fazendo uma distribuição manual usando os aptos da JSM 11/079.
Anulei a desginação dos cidadãos da JSM 12/077 para o TG.

A 4 RM deveria ser avisada do problema e chamar o responsável no TG para se responsabilizar pelo problema criado ao não cadastrar o endereço de sua OM corretamente. Ainda está incorreto, eu não arrumei o endereço.

Existe um relatório no sistema que lista os distribuídas da RM por OM/JSM onde é possível verificar se tem alguma OM recebendo de JSM que não está em sua jurisdição. É só ter um pouco de paciência e conferir as coisas.

Será que tenho que conferir a distribuição de todas as OM / JSM e todas as RM?
