### ISSUE TITLE
Portal e alistamento tem metodo alistar diferentes

### ISSUE THREAD

**Issue by 6975usa** [SERMIL/portal#51]
Ha duas AlistamentoServico.java. 
Consequentemente ha dois metodos "alistar" diferentes.
O alistamento tem que ser o mesmo nao importa se ele ta sendo feito online ou no Sermil.
Ha uma grande chance de haver incoerencias desse jeito. E a manutencao tambem se torna maior.

Sugiro unificarmos a AlistamentoServico.java e a colocarmos no core.
Gostaria de discutir isso com o Cel A. Lopes no dia 09Jun15.

**Comment by wagnerlopes** [comment]
Vamos implementar na versão 5.1.16, fazendo o refactor das classes para o sermil-core.
