### ISSUE TITLE
Pesquisa Cidadão

### ISSUE THREAD

**Issue by fabiosampaio12** [SERMIL/portal#53]
O sistema está apresentando erro ao tentar abrir a ficha do cidadão, após a pesquisa de  alguns RA's, ou seja, através do menu CIDADÃO/PESQUISAR é feito a pesquisa e encontrado o cidadão, porém, ao clicar no número de RA para verificar os dados do cidadão é apresentado a mensagem de erro anexa. 
Segue abaixo alguns números de Ra que estão apresentando problema:
250445891261
![erro pesquisa cidadao](https://cloud.githubusercontent.com/assets/12251958/7968058/b18c68d2-0a04-11e5-9bec-43689c1668f1.jpg)
251424291770

**Comment by wagnerlopes** [comment]
Solucionado. 
Acertei o mapeamento das colunas em CID_CERTIFICADO no banco de dados, para evitar o cadastramento de certificados com dados incorretos nas colunas ENTREGUE e ANULADO.
