### ISSUE TITLE
Cadastro cidadão

### ISSUE THREAD

**Issue by fabiosampaio12** [SERMIL/portal#55]
Informo-vos que está ocorrendo o seguinte erro ao tentar obter as informações de alguns alistados carregados no SERMIL:

Exception Description: The object [N], of class [class java.lang.String], from mapping [org.eclipse.persistence.mappings.DirectToFieldMapping[anulado-->CID_CERTIFICADO.ANULADO]] with descriptor [RelationalDescriptor(br.mil.eb.sermil.modelo.CidCertificado --> [DatabaseTable(CID_CERTIFICADO)])], could not be converted to [class java.lang.Integer].
Internal Exception: java.lang.NumberFormatException: For input string: "N"

Segue dois RA para a visualização do problema:
160662041559
160442873586

**Comment by wagnerlopes** [comment]
Resolvido na versão 5.1.15.
