### ISSUE TITLE
Erro alteração cadastro

### ISSUE THREAD

**Issue by fabiosampaio12** [SERMIL/portal#56]
Informo que no e-mail do suporte técnico ao usuários, chegaram várias mensagens informando que ao  tentar alterar os dados de militares já cadastrados no sistema. Exemplo: alteração da graduação de um militar já licenciado para posterior emissão de Certidão de Situação Militar, após clicar em "Salvar", aparece a mensagem de erro, conforme o documento anexo.
![erro1](https://cloud.githubusercontent.com/assets/12251958/8043405/52e34f84-0dfc-11e5-8078-ba9f22549e48.jpg)

**Comment by wagnerlopes** [comment]
Resolvido na versão 5.1.15.
