### ISSUE TITLE
Relatório de Boleto (CEF/ECT) com erro

### ISSUE THREAD

**Issue by wagnerlopes** [SERMIL/portal#61]
Acertar código númerico em cima do código de barras, está faltando o DV dos quatro grupos apresentados.

**Comment by wagnerlopes** [comment]
Corrigido.

**Comment by raseng** [comment]
Boa tarde Cel
Estamos com dúvida.
O Cap Pantoja e Alberto tentaram pagar alguns centavos e apareceu que:
1 - quando paga a taxa não aceita pagar multa com o mesmo CPF e vice-versa.
A imagem do pagamento realzaido e da recusa de pagamento serão encaminhados via e-mail.
TC Aquino

**Comment by wagnerlopes** [comment]
Pode anexar aqui as imagens dos documentos para mantermos o histórico dos problemas ocorridos e soluções implementadas.

**Comment by wagnerlopes** [comment]
Talvez seja por isso que o CNPJ era diferente para multas e taxas, porque pode ser que não fosse possível realizar pagamentos distintos com mesmo CNPJ. 
Eu posso implementar uma solução usando mesmo CNPJ e mesmo CPF, mas colocando um código extra no campo de identificação anterior ao CPF, onde taxa será código 1 e multa código 2.
Vou alterar o sistema e vocês testam quando eu der o "OK".

**Comment by raseng** [comment]
Ok.

**Comment by wagnerlopes** [comment]
Alterei o código para gerar boletos diferenciados para Taxa/Multa do mesmo CPF.
