### ISSUE TITLE
Nome da autoridade assinante do CAM precisa ser editavel

### ISSUE THREAD

**Issue by 6975usa** [SERMIL/portal#64]
1) Cidadao se alista numa reparticao consular.
2) Cidadao pede segunda via de CAM em outra reparticao consular.
Problema: O nome da autoridade assinante pernamece o nome da primeira reparticao consular. 
A autoridade assinante precisa ser editada.

**Comment by wagnerlopes** [comment]
Autoridade assinante é editável nas configurações da JSM.
Quando o cidadao aparece em outra repartiçao consular, o operador deve alterar a vinculaçao de JSM do cidadao para a da repartição consular onde está ocorrendo apresentação e depois emitir o CAM.

**Comment by wagnerlopes** [comment]
Não é o caso de alterar o sistema por causa disso, é questão de padronizar procedimento.
