### ISSUE TITLE
Atualização Cadastro  - ERRO

### ISSUE THREAD

**Issue by fabiosampaio12** [SERMIL/portal#77]
Solicito-vos ver a possibilidade de sanar o erro que aparece no campo (CADASTRAR) adicionar uma habilitação ao militar, ao selecionar um curso e clicar em salvar, está aparecendo um erro e não salva.

Exemplo: O usuário está tentando cadastrar o curso de AVANÇADO DE BLINDADOS (EB H01), no campo HABILITAÇÃO, para o General CASTRO e está aparecendo uma mensagem de erro (Erro inesperado durante a execução da solicitação). 

 Mensagem de erro:
   Acesso negado

**Comment by wagnerlopes** [comment]
Fiz a correção no código para sair na versão 5.1.17.
