### ISSUE TITLE
Falta um digito no RA da Ficha Cadastro

### ISSUE THREAD

**Issue by 6975usa** [SERMIL/portal#8]
O PDF de ficha cadastro do cidadao nao imprime o ultimo digito.

**Comment by wagnerlopes** [comment]
- Aumentar a caixa de texto para apresentar o dígito que falta; ou
- Diminuir o tamanho da fonte do campo RA.

**Comment by 6975usa** [comment]
Aumentado o campo RA da Ficha Cadastro
Resolvido.
