### ISSUE TITLE
Relatórios 8051 e 8114 

### ISSUE THREAD

**Issue by fabiosampaio12** [SERMIL/portal#81]
Solicito a possibilidade de verificar e caso seja necessário atualizar o Rel 8051 por escolaridade de acordo com o Rel 8114 Mapa de alistamento, pois ambos estão divergentes, para RM proceder com parâmetros da pré dispensa com atualização das JSM correspondentes. Informo ainda, que algumas JSM tributárias novas, não estão aparecendo na listagem para RM lançar a quantidade de fichas e a escolaridade de corte.

**Comment by wagnerlopes** [comment]
JSM novas foram incluídas.
Relatório 8051 e 8114 foram criados em épocas diferentes, com finalidades diferentes, para realizar a dispensa era utilizado apenas o Rel 8051. Não sei porque mandaram criar o 8114.
Cadê o SIG com as ferramentas de apoio a decisão? Era para o QlikView suprir essa necessidade, o CDS não deixou, manda ver com o pessoal do SIG cadê o relatório gerencial de alistados por escolaridade. Disseram que iam fazer tudo, estamos a 4 ou 5 anos esperando.

**Comment by wagnerlopes** [comment]
Atualizei os relatórios para ver se melhora para as RM. Mas não verifiquei se está tudo certo.

**Comment by fabiosampaio12** [comment]
O relatório 8051 ainda está desatualizado, ou seja, está faltando algumas juntas tributárias, portanto, inviabiliza o trabalho da RM no lançamento da quantidade de fichas para CS.
