### ISSUE TITLE
QC de unidades de defesa territorial

### ISSUE THREAD

**Issue by fabiosampaio12** [SERMIL/portal#82]
Estamos recebendo  varias solicitações para a criação dos QC de unidades de defesa territorial no portal do SERMIL,portanto, gostaria de verificar a possibilidade de criação das mesmas, conforme segue:

a. BTL GD TER/11 RC MEC - 9ª RM;
b. CIA GD TER/11 RC MEC - 9ª RM; 
c. PEL GD AQTL/11 RC MEC - 9ª RM
d.  Cia GD Ter/23º BC - 10ª RM

**Comment by wagnerlopes** [comment]
Vou criar os QC, mas como estamos na fase de pré-seleção, foi dar prioridade a isso nessa e na próxima semana. Vou deixar aberto o pedido pra não esquecermos.
