### ISSUE TITLE
Alocação eficiente de objetos

### ISSUE THREAD

**Issue by wagnerlopes** [SERMIL/portal#9]
Um problema que com certeza está deixando o aplicativo sobrecarregado é a maneira como as entidades gerenciadas pela JPA, ou seja todas as constantes do modelo, trata os objetos associados.

Ex: cidadao com arraylist de cid_evento, cid_documento, etc.

Atualmente a solução foi carregar os objetos agregados com **FetchType.EAGER** gerando overhead na alocação dos objetos, sendo que o melhor seria usar FetchType.LAZY (default).
Gostaria de incluir o suporte da **JPA 2.1 de Entity Graph** como está descrito [aqui] (http://www.thoughts-on-java.org/jpa-21-entity-graph-part-1-named-entity/) neste documento. Seria um melhoramento iria aliviar a aplicacação e a alocação de memória da JVM e por extensão do servidor.

**Comment by 6975usa** [comment]
Bom
Vou ler o artigo e retorno minha opiniao. Mas mesmo antes de ler o artigo
posso dizer que EAGER realmente sobrecarrega muito mais o servidor de
aplicacao.

2015-04-29 13:40 GMT-03:00 Wagner Lopes <notifications@github.com>:

**Comment by 6975usa** [comment]
Podemos discutir esse artigo quando o sr chegar na 2Feira. Nao entendi
muito o artigo.

A secao recebeu uma STT de informatica. Ela parece que tem potencial.

Att

2015-04-29 16:22 GMT-03:00 Eric <6975.usa@gmail.com>:

**Comment by wagnerlopes** [comment]
Esta opção de Entity Graph, ou seja grafos de objetos, foi uma melhoria incorporada na JPA a partir da versão 2.1, antes não tinha, por isso não era possível implementar no sermil. Já tem um tempo que estou pensando em incorporar a tecnologia no sistema, acho que desde do meio do ano passado, mas faltou tempo, e com as pendências que vão surgindo sempre empurro pra frente.
Mas com a necessidade de ganho de eficiência do servidor,está se tornando uma questão importante. Até trocarem o servidor ainda vai tempo, e temos que dar uma resposta mais rápida na disponibilidade da aplicação. Vamos estudando o assunto. Semana que vem discutimos. Segundo chego depois do almoço aí na DSM.
