### ISSUE TITLE
Delegacia - Cadastro

### ISSUE THREAD

**Issue by 6975usa** [SERMIL/portal#94]
Erro na alteracao do cadastro da Delegacia:

 Erro inesperado durante a execução da solicitação.

Suporte Técnico: sermilweb@dgp.eb.mil.br

   Mensagem de erro:
   Could not commit JPA transaction; nested exception is javax.persistence.RollbackException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.6.0.v20150309-bf26070): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: java.sql.SQLDataException: ORA-01438: valor maior que a precisão especificada usado para esta coluna

Error Code: 1438
Call: UPDATE DELEGACIA SET LATITUDE = ?, LONGITUDE = ? WHERE ((CODIGO = ?) AND (CSM_CODIGO = ?))
	bind => [-7221497.0, -3.5883856E7, 5, 23]
Query: UpdateObjectQuery(23/005 - 5 DELEGACIA DO SERVICO MILITAR DA 23 C S M)

**Comment by wagnerlopes** [comment]
Erro está aqui -3.5883856E7 , usuário tentando carregar longitude com notação exponencial. Tem que ser notação decimal pura.
