### ISSUE TITLE
Alistamento Online

### ISSUE THREAD

**Issue by fabiosampaio12** [SERMIL/portal#97]
A 19 CSM entrou em contato informando que os cidadãos que estão fazendo alistamento online após 01 de julho de 2015, o sistema automaticamente está enviando para Excesso de Contingente e enquadrando como alistamento dentro do prazo. O que deveria acontecer apenas com cidadãos alistados até último dia útil do mês de junho.

**Comment by wagnerlopes** [comment]
Esclarecendo,
Fiz uma consulta no banco de dados e os cidadãos alistados fora do prazo estão como alistados, apenas aqueles que se alistam em Municipio não tributário estão sendo colocados como Dispensados de Seleção automaticamente, o que é o mesmo comportamento do alistamento feito na JSM.
Alistados em MNT fica assim o cadastro: situacao_militar = 3 (dispensado de seleção), dispensa = 1 (MNT).
