### ISSUE TITLE
Inclusao de Local de emissao e Data no Cert Sit Militar

### ISSUE THREAD

**Issue by 6975usa** [SERMIL/portal#98]
O Cmt do IME solicita a inclusao de local de emissao de data no Cert Sit Mil
Esse cmt sita a NT-01, Art 34 e Anexo C cuja foto esta abaixo:
![cert sit mil](https://cloud.githubusercontent.com/assets/6667748/8776733/b344a100-2ec9-11e5-80db-9f2a9ea57d4d.png)

**Comment by fabiosampaio12** [comment]
O S1 do IME informa que o Comandante não quer assinar a Certidão de Situação Militar gerada pelo SERMIL, pois não apresenta local e data de emissão e estão com vários pedidos de certidões para serem emitidos, inclusive cidadão querendo emitir passaporte para viagem ao exterior e estão impossibilitados devido à recusa do comandante em assinar certidão diferente. Solicita posição de prazo para disponibilidade.

**Comment by 6975usa** [comment]
Local e data incluídos na certidao:

Tambem foi criado um metodo para validar regras de negocio:


![csm](https://cloud.githubusercontent.com/assets/6667748/9178709/b41381b8-3f6e-11e5-9ac5-cc5a12573c5c.png)
