### ISSUE TITLE
ERRO AO LANÇAR ATIRADOR

### ISSUE THREAD

**Issue by aryene** [SERMIL/portal#99]
1º SGT LÁZARO ao LANÇAR TRANCAMENTO DE MATRICULA DE ATIRADOR, ocorreu um ERRO 

![erro sermil 2](https://cloud.githubusercontent.com/assets/3015989/8802120/a4f26d0e-2f95-11e5-9eb9-be9cf5594bd7.jpg)

**Comment by wagnerlopes** [comment]
Corrigido na versão 5.2.1, a ser lançada em breve.
